### ISSUE TITLE
Mailings Asistente Danica

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/DanicaWeb#10]
Fede: en tu dropbox carpeta Asistente Danica te subi 2 psd con mailings del asistente para maquetar. Se estan sincronizando en dropbox aun.

Mas tarde te sumo 3 mas. Por favor decime que los podes tener para mañana en algun momento.

Los que faltan son variaciones de estos dos.

Abrazo

**Comment by FAAREIA** [comment]
Joya Lea, ahi los vi.
Por suerte son bastante simples, el único problema que les veo es que son muy anchos.
Máximo 640px de ancho debería de ser. Pensá que el usuario lo va abrir en gmail o hotmail.

Si hay algo por cambiar con respecto a la imagen en base a esto que mencioné, avisa.

**Comment by mkreyness** [comment]
Fede por favor incluime los siguientes comentarios donde corresponda:

  (donde vaya el nombre y apellido de la persona, si 
es que se pone dentro)
 (si es que se pone dentro)
 donde va el link que tiene que seguir.

Gracias

**Comment by LeandroBraier** [comment]
Fede, lo podrás adaptar vos al ancho? No creo que haya problema con las
imagenes.

2014-03-11 16:35 GMT-03:00 mkreyness notifications@github.com:

> Fede por favor incluime los siguientes comentarios donde corresponda:
> 
>  (donde vaya el nombre y apellido de la persona, si
> es que se pone dentro)
>  (si es que se pone dentro)
>  donde va el link que tiene que seguir.
> 
> Gracias
> 
> On 11/03/2014 04:32 p.m., Federico Arena wrote:
> 
> > Joya Lea, ahi los vi.
> > Por suerte son bastante simples, el único problema que les veo es que
> > son muy anchos.
> > Máximo 640px de ancho debería de ser. Pensá que el usuario lo va abrir
> > en gmail o hotmail.
> > 
> > Si hay algo por cambiar con respecto a la imagen en base a esto que
> > mencioné, avisa.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/LeandroBraier/DanicaWeb/issues/10#issuecomment-37339604
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/LeandroBraier/DanicaWeb/issues/10#issuecomment-37339949
> .

## 

Leandro Braier
Producción Audiovisual & Social Media
Móvil 1158717399

**Comment by FAAREIA** [comment]
Si dale, decia nomas para que no haya sorpresas

**Comment by LeandroBraier** [comment]
Fede, ya subí todos los PSD necesarios. Decime para cuando los podrías tener maquetados. A medida que vayas teniendo algunos se los vas pasando a Marce como venís haciendo. Chequeá que sean en la carpeta correcta: DANICA MAQUETADOR/ ASISTENTE DANICA / MAILING.

**Comment by LeandroBraier** [comment]
ya están cargados

**Comment by FAAREIA** [comment]
Marce, te adelanto algunas cosas que estoy viendo y faltan los "token" o como se llamen:
- Link de baja a la suscripción
- Link del newsletter para abrirlo desde el navegador. Cada news se subirá también a una url del sitio.

Por ahora nada más
Voy actualizando a medida que avanzo
Abrazo

**Comment by mkreyness** [comment]
Pero a que llaman newsletter? El mail con las recetas personalizadas? Para desuscribirse del asistente habria q tener un boton en la pagina de settings del asistente y manejarlo desde ahi

Enviado desde mi iPhone

**Comment by LeandroBraier** [comment]
Totalmente de acuerdo. Implementemos un botón de DESACTIVAR ASISTENTE
DÁNICA a la izquierda y más chico que el ACTIVAR que aparecería solo cuando
alguien vuelve a acceder para modificar sus preferencias.

2014-03-12 12:29 GMT-03:00 mkreyness notifications@github.com:

> Pero a que llaman newsletter? El mail con las recetas personalizadas? Para
> desuscribirse del asistente habria q tener un boton en la pagina de
> settings del asistente y manejarlo desde ahi
> 
> Enviado desde mi iPhone
> 
> > El 12/03/2014, a las 12:18, Federico Arena notifications@github.com
> > escribió:
> > 
> > Marce, te adelanto algunas cosas que estoy viendo y faltan los "token" o
> > como se llamen:
> > 
> > Link de baja a la suscripción
> > Link del newsletter para abrirlo desde el navegador. Cada news se subirá
> > también a una url del sitio.
> > Por ahora nada más
> > Voy actualizando a medida que avanzo
> > Abrazo
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/LeandroBraier/DanicaWeb/issues/10#issuecomment-37422032
> .

## 

Leandro Braier
Producción Audiovisual & Social Media
Móvil 1158717399

**Comment by FAAREIA** [comment]
Confirmenme el html que les mandé por mail y avanzo con los otros 2 hoy.

**Comment by LeandroBraier** [comment]
ahi te respondi por mail las correcciones

2014-03-12 14:11 GMT-03:00 Federico Arena notifications@github.com:

> Confirmenme el que les mandé por mail y avanzo con los otros 2 hoy.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/LeandroBraier/DanicaWeb/issues/10#issuecomment-37435773
> .

## 

Leandro Braier
Producción Audiovisual & Social Media
Móvil 1158717399

**Comment by mkreyness** [comment]
Esta parte quedó medio fuera de thread.

Yo actualmente al boton de "Activar Asistente" le cambio el texto por 
"Confirmar Datos" cuando es alguien que ya lo tiene activo. En caso de 
que alguien ya desctivado ingrese para "reactivarlo", volveria a decir 
"Activar Asistente" y el de desactivar deberia estar deshabilitado o 
invisible.

Fede: podras agregarle al template que estoy usando (en la carpeta 
public_html/html como siempre) que es el asistente-danicaT.html, el 
boton de "Desactivar Asistente" donde corresponda ? Yo con eso me arreglo.
Si quieren se puede dejar el link de "desuscribirse" (porque la gente 
busca eso), pero que apunte al mismo lugar que el de "modificar 
preferencias".

**Comment by LeandroBraier** [comment]
Por mi perfecto.

2014-03-12 16:16 GMT-03:00 mkreyness notifications@github.com:

> Esta parte quedó medio fuera de thread.
> 
> Yo actualmente al boton de "Activar Asistente" le cambio el texto por
> "Confirmar Datos" cuando es alguien que ya lo tiene activo. En caso de
> que alguien ya desctivado ingrese para "reactivarlo", volveria a decir
> "Activar Asistente" y el de desactivar deberia estar deshabilitado o
> invisible.
> 
> Fede: podras agregarle al template que estoy usando (en la carpeta
> public_html/html como siempre) que es el asistente-danicaT.html, el
> boton de "Desactivar Asistente" donde corresponda ? Yo con eso me arreglo.
> Si quieren se puede dejar el link de "desuscribirse" (porque la gente
> busca eso), pero que apunte al mismo lugar que el de "modificar
> preferencias".
> 
> On 12/03/2014 12:38 p.m., LeandroBraier wrote:
> 
> > Totalmente de acuerdo. Implementemos un botón de DESACTIVAR ASISTENTE
> > DÁNICA a la izquierda y más chico que el ACTIVAR que aparecería solo
> > cuando
> > alguien vuelve a acceder para modificar sus preferencias.
> > 
> > 2014-03-12 12:29 GMT-03:00 mkreyness notifications@github.com:
> > 
> > > Pero a que llaman newsletter? El mail con las recetas
> > > personalizadas? Para
> > > desuscribirse del asistente habria q tener un boton en la pagina de
> > > settings del asistente y manejarlo desde ahi
> > > 
> > > Enviado desde mi iPhone
> > > 
> > > > El 12/03/2014, a las 12:18, Federico Arena <notifications@github.com
> > > 
> > > escribió:
> > > 
> > > > Marce, te adelanto algunas cosas que estoy viendo y faltan los
> > > > "token" o
> > > > como se llamen:
> > > > 
> > > > Link de baja a la suscripción
> > > > Link del newsletter para abrirlo desde el navegador. Cada news se
> > > > subirá
> > > > también a una url del sitio.
> > > > Por ahora nada más
> > > > Voy actualizando a medida que avanzo
> > > > Abrazo
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub.
> > > 
> > > —
> > > Reply to this email directly or view it on
> > > GitHub<
> > > https://github.com/LeandroBraier/DanicaWeb/issues/10#issuecomment-37422032
> > > 
> > > .
> > 
> > ## 
> > 
> > Leandro Braier
> > Producción Audiovisual & Social Media
> > Móvil 1158717399
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/LeandroBraier/DanicaWeb/issues/10#issuecomment-37423276
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/LeandroBraier/DanicaWeb/issues/10#issuecomment-37451685
> .

## 

Leandro Braier
Producción Audiovisual & Social Media
Móvil 1158717399

**Comment by FAAREIA** [comment]
Mmmmmm, no se a que te referis con lo del lugar de de "modificar preferencias", pero fijense que ya agregué el botón de desuscripción:

http://danica.com.ar/danica/asistente-danica311.html

En el Template tuyo Marce, también esta agregado.

Avisame si te sirve asi.

**Comment by LeandroBraier** [comment]
Fede, el botón de desactivar no debería aparecer en la primer página del
Asistente. Solo el botón de activar.

En el html que aparece cuando volvemos a "modificar los datos" ahí si
aparecería. El botón de "activar" se convertiría en "modificar
preferencias" y el botón de "desactivar asistente dánica" tiene que ser más
pequeño y con un color más suave. Si querés te hago el PSD Fede. Decime si
lo necesitás.

2014-03-12 16:56 GMT-03:00 Federico Arena notifications@github.com:

> Mmmmmm, no se a que te referis con lo del lugar de de "modificar
> preferencias", pero fijense que ya agregué el botón de desuscripción:
> 
> http://danica.com.ar/danica/asistente-danica311.html
> 
> En el Template tuyo Marce, también esta agregado.
> 
> Avisame si te sirve asi.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/LeandroBraier/DanicaWeb/issues/10#issuecomment-37456215
> .

## 

Leandro Braier
Producción Audiovisual & Social Media
Móvil 1158717399

**Comment by FAAREIA** [comment]
Dale, si esta en PSD buenisimo. Igual ahi lo muestro para que lo vean, marce luego lo pone o no visible.

**Comment by LeandroBraier** [comment]
Ok, mandame el PSD ultima version del Asistente, prque el que está en el
Dropbox es viejo.

On Wed, Mar 12, 2014 at 5:17 PM, Federico Arena notifications@github.comwrote:

> Dale, si esta en PSD buenisimo. Igual ahi lo muestro para que lo vean,
> marce luego lo pone o no visible.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/LeandroBraier/DanicaWeb/issues/10#issuecomment-37458636
> .

## 

Leandro Braier
Producción Audiovisual & Social Media
Móvil 1158717399
