### ISSUE TITLE
Mailing del asistente - Preferencias, suscriptos, confirmación

### ISSUE THREAD

**Issue by FAAREIA** [LeandroBraier/DanicaWeb#12]
Pongan aca lo que haga falta cambiar.
Por ahora estamos probando el mailing.

**Comment by LeandroBraier** [comment]
Además, en el Subject del mail dice:
"Ya podes activar tu Asistente Danica" 
y debe decir:
"Ya podés activar tu Asistente Dánica"

**Comment by mkreyness** [comment]
Asi habia puesto en un principio y cuando hice pruebas a veces me 
llegaban marcados como [SPAM](creo que en mi cuenta de Fibertel).
Probé de sacarlos y nunca mas dijo [SPAM].
Si quieren los repongo y vemos como les llega a ustedes.

**Comment by mkreyness** [comment]
Para recibir el resto tenes que seguir el proceso: activar, modificar, etc.

**Comment by LeandroBraier** [comment]
Todo me funciona perfecto en los 3 mailings:

. solo que permanece ese desplazamiento (aun haiendo apretado F5)
. donde dice "HACE CLIC" debería decir "HACÉ CLIC"

**Comment by FAAREIA** [comment]
Estas cacheado lea, esa imagen ya no existe porque tiene una franja blanca en la parte superior.
Entra aca http://danica.com.ar/mailing/medio.jpg -> dale F5 -> Entra nuevamente al mail.
Dale F5 al mailing también para que te actualicé

**Comment by LeandroBraier** [comment]
Lo hice y sigo viendo desplazado el texto

On Fri, Mar 14, 2014 at 2:08 PM, Federico Arena notifications@github.comwrote:

> Estas cacheado lea, esa imagen ya no existe porque tiene una franja blanca
> en la parte superior.
> Entra aca http://danica.com.ar/mailing/medio.jpg -> dale F5 -> Entra
> nuevamente al mail.
> Dale F5 al mailing también para que te actualicé
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/LeandroBraier/DanicaWeb/issues/12#issuecomment-37671869
> .

## 

Leandro Braier
Producción Audiovisual & Social Media
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Fede, recibí el sábado un mailing del asistente que en mobile veía bien pero en gmail lo veo sin fondo blanco en la foto de recetas. Esto no es prioritario, pero lo sumo para cuanod puedas revisarlo. abrazo
![captura de pantalla 2014-03-31 a la s 09 34 04](https://cloud.githubusercontent.com/assets/6719872/2567009/b22c1576-b8cf-11e3-89c6-95efac482384.png)
