### ISSUE TITLE
Mailing Diario

### ISSUE THREAD

**Issue by FAAREIA** [LeandroBraier/DanicaWeb#14]
Pongan aca lo que haga falta

**Comment by FAAREIA** [comment]
tipos-comida-carne.png
tipos-comida-cerdo.png
tipos-comida-pollo.png
tipos-comida-pastas.png
tipos-comida-pescado.png
tipos-comida-vegetariano.png

Los tamaños de las imágenes son:
- Principal: 350x200
- Secundarias: 143x90

**Comment by LeandroBraier** [comment]
Por ahora en desuso.
Reabrir cuando sea necesario.
