### ISSUE TITLE
Logo Asistente en Home

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/DanicaWeb#18]
Fede, te subí un pequeño agregado para la colocación del Logo del Asistente Dánica en la home. Me lo pidió Eze. Es la estrella que tenía el logo anterior con el mensaje "Activalo ya".

**Comment by FAAREIA** [comment]
Hola Lea, en que ruta esta el agregado?

**Comment by FAAREIA** [comment]
Subido

**Comment by LeandroBraier** [comment]
Gracias Fede!

**Comment by LeandroBraier** [comment]
Fede, no veo el logo del asistente en la home.

**Comment by FAAREIA** [comment]
F5, ctrl+F5, clear cache.
Estuve averiguando hace unas semanas y no puedo forzarle la borrada de caché al usuario, por lo que es cuestion de tiempo para el que lo tiene cacheado. O si apreta esas teclas.
