### ISSUE TITLE
6 mailings con producto

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/DanicaWeb#19]
Fede, ya te subí los templates. En total son 6:

Mailing Diario
Mailing cada dos días
Mailing cada tres días
Mailing cada cuatro días
Mailing cada cinco días
Mailing cada seis días
- Mailing semanal ya maquetado y testeado que van sin productos

**Comment by FAAREIA** [comment]
Ahi vi que estan apareciendo!

**Comment by LeandroBraier** [comment]
En el path de ASISTENTE DANICA/ MAILINGS

Todavía se está sincronizando, pero ya tenés un par online. Son todos sobre
la misma estructura del semanal pero hay diferencias en las fotos y en
algunos textos.

2014-03-18 21:54 GMT-03:00 Federico Arena notifications@github.com:

> En que path estan lea?
> No los veo en donde estaban los otros, los estas subiendo?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/LeandroBraier/DanicaWeb/issues/19#issuecomment-38007115
> .

## 

Leandro Braier
Producción Audiovisual & Social Media
Móvil 1158717399

**Comment by FAAREIA** [comment]
Lea, estaba viendo que la frase de los mailing la estas ajustando para que entre en los bloques que ocupa el producto. Si bien yo lo entiendo porque conozco la situación, no sería mejor buscar una frase genérica? A simple vista parece que la frase llega hasta ahi por la longitud y no que "cubre" a los productos.
O sino ponerle un icono de "producto dánica", tienen alguno?

**Comment by LeandroBraier** [comment]
Como decís de hacerlo? Agregar un elemento gráfico?

2014-03-19 10:25 GMT-03:00 Federico Arena notifications@github.com:

> Lea, estaba viendo que la frase de los mailing la estas ajustando para que
> entre en los bloques que ocupa el producto. Si bien yo lo entiendo porque
> conozco la situación, no sería mejor buscar una frase genérica? A simple
> vista parece que la frase llega hasta ahi por la longitud y no que "cubre"
> a los productos.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/LeandroBraier/DanicaWeb/issues/19#issuecomment-38049652
> .

## 

Leandro Braier
Producción Audiovisual & Social Media
Móvil 1158717399

**Comment by FAAREIA** [comment]
Capas que podría ser asi, es mínimo pero simple. Lo del ícono sería aun mejor pero va a ser dificil definir uno, y que quede distinto a los otros tmb.
![danica](https://f.cloud.github.com/assets/6184969/2460653/c1fca346-af6d-11e3-9dd1-0c35e93ad71f.jpg)

¿Algo asi? En algunos productos no se ve tan bien el logo como en las mantecas, ej: tapas

**Comment by LeandroBraier** [comment]
Lo que veo es el texto "producto Dánica?" como en gris clarito. No me gusta
mucho. Era eso?

Sino dame un rato y pienso una alternativa.

2014-03-19 10:56 GMT-03:00 Federico Arena notifications@github.com:

> Capas que podría ser asi, es mínimo pero simple. Lo del ícono sería aun
> mejor pero va a ser dificil definir uno, y que quede distinto a los otros
> tmb.
> [image: danica]https://f.cloud.github.com/assets/6184969/2460653/c1fca346-af6d-11e3-9dd1-0c35e93ad71f.jpg
> 
> ¿Algo asi?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/LeandroBraier/DanicaWeb/issues/19#issuecomment-38052788
> .

## 

Leandro Braier
Producción Audiovisual & Social Media
Móvil 1158717399

**Comment by FAAREIA** [comment]
Mmmmmm, fijate este link por si no ves la imagen:
https://f.cloud.github.com/assets/6184969/2460653/c1fca346-af6d-11e3-9dd1-0c35e93ad71f.jpg

Le agregue la marca dánica arriba del producto, entre los ganchos que ahora son rojos.
Los templates ya los tengo preparados, para agregarle el cambio que hagamos

**Comment by LeandroBraier** [comment]
Aaaaaahhh recién caigo.... Entonces arriba no le agregarías texto decís?

Me gusta lo que hiciste con eso, pero de todas formas en algún lado hay que
aclarar que son productos. Sumale ese diseño al texto que te pasé y, si
querés, probamos el texto en rojo.

2014-03-19 11:57 GMT-03:00 Federico Arena notifications@github.com:

> Mmmmmm, fijate este link por si no ves la imagen:
> 
> https://f.cloud.github.com/assets/6184969/2460653/c1fca346-af6d-11e3-9dd1-0c35e93ad71f.jpg
> 
> Le agregue la marca dánica arriba del producto, entre los ganchos que
> ahora son rojos.
> Los templates ya los tengo preparados, para agregarle el cambio que hagamos
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/LeandroBraier/DanicaWeb/issues/19#issuecomment-38060201
> .

## 

Leandro Braier
Producción Audiovisual & Social Media
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Marce, cuando puedas aplicá el mailing de producto ya final. abrazo

**Comment by mkreyness** [comment]
yo para no sumar dolores de cabeza, si se puede, lo dejaria para despues 
de lanzamiento de la Experiencia Danica.

**Comment by LeandroBraier** [comment]
Ok.

2014-03-31 14:15 GMT-03:00 mkreyness notifications@github.com:

> yo para no sumar dolores de cabeza, si se puede, lo dejaria para despues
> de lanzamiento de la Experiencia Danica.
> 
> On 31/03/2014 09:23 a.m., LeandroBraier wrote:
> 
> > Marce, cuando puedas aplicá el mailing de producto ya final. abrazo
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/LeandroBraier/DanicaWeb/issues/19#issuecomment-39081890
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/LeandroBraier/DanicaWeb/issues/19#issuecomment-39114727
> .

## 

Leandro Braier
Producción Audiovisual & Social Media
Móvil 1158717399
