### ISSUE TITLE
Backup Sitio Danica

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/DanicaWeb#20]
Marce, necesitaría un backup completo del sitio actual de Danica, con recetas, fotos, videos incluidos, etc, para pasarle al cliente. COmo te parece hacerlo?

**Comment by mkreyness** [comment]
Programas y base de datos incluidos ?
CMS ?
Videos te referis a los de las cabinas tambien ?

No creo que tengamos lugar en el propio sitio para hacer una copia 
comprimida de TODO, y levantarlo seria tambien hiperpesado.
Sin lo de cabinas, es mas manejable.

**Comment by LeandroBraier** [comment]
Es sin cabinas y sin "amamoscocinarconvos.com". Solo "danica.com.ar". Eso
es posible?

2014-04-22 17:10 GMT-03:00 mkreyness notifications@github.com:

> Programas y base de datos incluidos ?
> CMS ?
> Videos te referis a los de las cabinas tambien ?
> 
> No creo que tengamos lugar en el propio sitio para hacer una copia
> comprimida de TODO, y levantarlo seria tambien hiperpesado.
> Sin lo de cabinas, es mas manejable.
> 
> On 22/04/2014 04:37 p.m., LeandroBraier wrote:
> 
> > Marce, necesitaría un backup completo del sitio actual de Danica, con
> > recetas, fotos, videos incluidos, etc, para pasarle al cliente. COmo
> > te parece hacerlo?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/LeandroBraier/DanicaWeb/issues/20.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/LeandroBraier/DanicaWeb/issues/20#issuecomment-41089331
> .

## 

Leandro Braier
Producción Audiovisual & Social Media
Móvil 1158717399

**Comment by mkreyness** [comment]
Es medio complicado porque comparten cosas.
Pero CMS de Danica tambien ? O sea, no entiendo si lo que quieren son 
paginas estaticas o los programas que las producen, la base de datos, etc.

**Comment by LeandroBraier** [comment]
Quieren los contenidos en sí, no hace falta el cms. Esto prácticamente
implica las cargas de productos y recetas. Los demás lo bajo como HTML
estimo.

2014-04-22 18:01 GMT-03:00 mkreyness notifications@github.com:

> Es medio complicado porque comparten cosas.
> Pero CMS de Danica tambien ? O sea, no entiendo si lo que quieren son
> paginas estaticas o los programas que las producen, la base de datos, etc.
> 
> On 22/04/2014 05:28 p.m., LeandroBraier wrote:
> 
> > Es sin cabinas y sin "amamoscocinarconvos.com". Solo "danica.com.ar".
> > Eso
> > es posible?
> > 
> > 2014-04-22 17:10 GMT-03:00 mkreyness notifications@github.com:
> > 
> > > Programas y base de datos incluidos ?
> > > CMS ?
> > > Videos te referis a los de las cabinas tambien ?
> > > 
> > > No creo que tengamos lugar en el propio sitio para hacer una copia
> > > comprimida de TODO, y levantarlo seria tambien hiperpesado.
> > > Sin lo de cabinas, es mas manejable.
> > > 
> > > On 22/04/2014 04:37 p.m., LeandroBraier wrote:
> > > 
> > > > Marce, necesitaría un backup completo del sitio actual de Danica, con
> > > > recetas, fotos, videos incluidos, etc, para pasarle al cliente. COmo
> > > > te parece hacerlo?
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > https://github.com/LeandroBraier/DanicaWeb/issues/20.
> > > 
> > > —
> > > Reply to this email directly or view it on
> > > GitHub<
> > > https://github.com/LeandroBraier/DanicaWeb/issues/20#issuecomment-41089331
> > > 
> > > .
> > 
> > ## 
> > 
> > Leandro Braier
> > Producción Audiovisual & Social Media
> > Móvil 1158717399
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/LeandroBraier/DanicaWeb/issues/20#issuecomment-41091498
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/LeandroBraier/DanicaWeb/issues/20#issuecomment-41095224
> .

## 

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
Ok, entonces con copiar los HTML y las cosas que referencian (fotos y 
unos pocos videos) alcanzaria.
Hay cosas que son programas (por ejemplo el Search), pero lo que traen 
es el mismo contenido.
Te armo un .zip ?

**Comment by LeandroBraier** [comment]
Dale, porfa. Con eso estaríamos por el momento para ese backup. Gracias!

2014-04-22 19:31 GMT-03:00 mkreyness notifications@github.com:

> Ok, entonces con copiar los HTML y las cosas que referencian (fotos y
> unos pocos videos) alcanzaria.
> Hay cosas que son programas (por ejemplo el Search), pero lo que traen
> es el mismo contenido.
> Te armo un .zip ?
> 
> On 22/04/2014 07:28 p.m., LeandroBraier wrote:
> 
> > Quieren los contenidos en sí, no hace falta el cms. Esto prácticamente
> > implica las cargas de productos y recetas. Los demás lo bajo como HTML
> > estimo.
> > 
> > 2014-04-22 18:01 GMT-03:00 mkreyness notifications@github.com:
> > 
> > > Es medio complicado porque comparten cosas.
> > > Pero CMS de Danica tambien ? O sea, no entiendo si lo que quieren son
> > > paginas estaticas o los programas que las producen, la base de
> > > datos, etc.
> > > 
> > > On 22/04/2014 05:28 p.m., LeandroBraier wrote:
> > > 
> > > > Es sin cabinas y sin "amamoscocinarconvos.com". Solo "danica.com.ar
> > > > ".
> > > > Eso
> > > > es posible?
> > > > 
> > > > 2014-04-22 17:10 GMT-03:00 mkreyness notifications@github.com:
> > > > 
> > > > > Programas y base de datos incluidos ?
> > > > > CMS ?
> > > > > Videos te referis a los de las cabinas tambien ?
> > > > > 
> > > > > No creo que tengamos lugar en el propio sitio para hacer una copia
> > > > > comprimida de TODO, y levantarlo seria tambien hiperpesado.
> > > > > Sin lo de cabinas, es mas manejable.
> > > > > 
> > > > > On 22/04/2014 04:37 p.m., LeandroBraier wrote:
> > > > > 
> > > > > > Marce, necesitaría un backup completo del sitio actual de
> > > > > > Danica, con
> > > > > > recetas, fotos, videos incluidos, etc, para pasarle al
> > > > > > cliente. COmo
> > > > > > te parece hacerlo?
> > > > > > 
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub
> > > > > > https://github.com/LeandroBraier/DanicaWeb/issues/20.
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on
> > > > > GitHub<
> > 
> > https://github.com/LeandroBraier/DanicaWeb/issues/20#issuecomment-41089331
> > 
> > > > > .
> > > > 
> > > > ## 
> > > > 
> > > > Leandro Braier
> > > > Producción Audiovisual & Social Media
> > > > Móvil 1158717399
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > 
> > https://github.com/LeandroBraier/DanicaWeb/issues/20#issuecomment-41091498
> > 
> > > > .
> > > 
> > > —
> > > Reply to this email directly or view it on
> > > GitHub<
> > > https://github.com/LeandroBraier/DanicaWeb/issues/20#issuecomment-41095224
> > > 
> > > .
> > 
> > ## 
> > 
> > Leandro Braier
> > Producción Audiovisual & Social Media
> > Benteveo Producciones http://benteveo.tv
> > 
> > Móvil 1158717399
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/LeandroBraier/DanicaWeb/issues/20#issuecomment-41103879
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/LeandroBraier/DanicaWeb/issues/20#issuecomment-41104135
> .

## 

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
ok, esta noche lo armo y en todo caso te lo dejo para levantar por FTP ? 
Porque seguro va a ser enorme para mandar por mail.

**Comment by LeandroBraier** [comment]
Dale, me parece bien por ftp. Mandame los datos de acceso cuando lo tengas.
abrazo

2014-04-22 20:00 GMT-03:00 mkreyness notifications@github.com:

> ok, esta noche lo armo y en todo caso te lo dejo para levantar por FTP ?
> Porque seguro va a ser enorme para mandar por mail.
> 
> On 22/04/2014 07:57 p.m., LeandroBraier wrote:
> 
> > Dale, porfa. Con eso estaríamos por el momento para ese backup. Gracias!
> > 
> > 2014-04-22 19:31 GMT-03:00 mkreyness notifications@github.com:
> > 
> > > Ok, entonces con copiar los HTML y las cosas que referencian (fotos y
> > > unos pocos videos) alcanzaria.
> > > Hay cosas que son programas (por ejemplo el Search), pero lo que traen
> > > es el mismo contenido.
> > > Te armo un .zip ?
> > > 
> > > On 22/04/2014 07:28 p.m., LeandroBraier wrote:
> > > 
> > > > Quieren los contenidos en sí, no hace falta el cms. Esto
> > > > prácticamente
> > > > implica las cargas de productos y recetas. Los demás lo bajo como
> > > > HTML
> > > > estimo.
> > > > 
> > > > 2014-04-22 18:01 GMT-03:00 mkreyness notifications@github.com:
> > > > 
> > > > > Es medio complicado porque comparten cosas.
> > > > > Pero CMS de Danica tambien ? O sea, no entiendo si lo que
> > > > > quieren son
> > > > > paginas estaticas o los programas que las producen, la base de
> > > > > datos, etc.
> > > > > 
> > > > > On 22/04/2014 05:28 p.m., LeandroBraier wrote:
> > > > > 
> > > > > > Es sin cabinas y sin "amamoscocinarconvos.com". Solo
> > > > > > "danica.com.ar
> > > > > > ".
> > > > > > Eso
> > > > > > es posible?
> > > > > > 
> > > > > > 2014-04-22 17:10 GMT-03:00 mkreyness notifications@github.com:
> > > > > > 
> > > > > > > Programas y base de datos incluidos ?
> > > > > > > CMS ?
> > > > > > > Videos te referis a los de las cabinas tambien ?
> > > > > > > 
> > > > > > > No creo que tengamos lugar en el propio sitio para hacer una
> > > > > > > copia
> > > > > > > comprimida de TODO, y levantarlo seria tambien hiperpesado.
> > > > > > > Sin lo de cabinas, es mas manejable.
> > > > > > > 
> > > > > > > On 22/04/2014 04:37 p.m., LeandroBraier wrote:
> > > > > > > 
> > > > > > > > Marce, necesitaría un backup completo del sitio actual de
> > > > > > > > Danica, con
> > > > > > > > recetas, fotos, videos incluidos, etc, para pasarle al
> > > > > > > > cliente. COmo
> > > > > > > > te parece hacerlo?
> > > > > > > > 
> > > > > > > > —
> > > > > > > > Reply to this email directly or view it on GitHub
> > > > > > > > https://github.com/LeandroBraier/DanicaWeb/issues/20.
> > > > > > > 
> > > > > > > —
> > > > > > > Reply to this email directly or view it on
> > > > > > > GitHub<
> > 
> > https://github.com/LeandroBraier/DanicaWeb/issues/20#issuecomment-41089331
> > 
> > > > > > > .
> > > > > > 
> > > > > > ## 
> > > > > > 
> > > > > > Leandro Braier
> > > > > > Producción Audiovisual & Social Media
> > > > > > Móvil 1158717399
> > > > > > 
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub
> > > > > > <
> > 
> > https://github.com/LeandroBraier/DanicaWeb/issues/20#issuecomment-41091498
> > 
> > > > > > .
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on
> > > > > GitHub<
> > 
> > https://github.com/LeandroBraier/DanicaWeb/issues/20#issuecomment-41095224
> > 
> > > > > .
> > > > 
> > > > ## 
> > > > 
> > > > Leandro Braier
> > > > Producción Audiovisual & Social Media
> > > > Benteveo Producciones http://benteveo.tv
> > > > 
> > > > Móvil 1158717399
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > 
> > https://github.com/LeandroBraier/DanicaWeb/issues/20#issuecomment-41103879
> > 
> > > > .
> > > 
> > > —
> > > Reply to this email directly or view it on
> > > GitHub<
> > > https://github.com/LeandroBraier/DanicaWeb/issues/20#issuecomment-41104135
> > > 
> > > .
> > 
> > ## 
> > 
> > Leandro Braier
> > Producción Audiovisual & Social Media
> > Benteveo Producciones http://benteveo.tv
> > Móvil 1158717399
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/LeandroBraier/DanicaWeb/issues/20#issuecomment-41106216
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/LeandroBraier/DanicaWeb/issues/20#issuecomment-41106458
> .

## 

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
```
ftp:
host: danica.com.ar
user: leandro
pass: benteveo
ahi te deje 3 zips, el de videos es enorme, porque hay uno de
cientoypico de megas que se llama "tarta ok" cargado hace unos 10
dias.
No se si tiene mucho sentido que lo levantes porque en definitiva
seguro que los videos vos ya los  tenes.
Avisame cuando pueda borrar todo porque estamos cortos de disco.El 22/04/2014 20:44, LeandroBraier
  escribió:
Dale, me parece bien por ftp. Mandame los datos de
  acceso cuando lo tengas.

  abrazo

  2014-04-22 20:00 GMT-03:00 mkreyness
  <notifications@github.com>:

  > ok, esta noche lo armo y en todo caso te lo dejo para
  levantar por FTP ?

  > Porque seguro va a ser enorme para mandar por mail.

  >

  >

  > On 22/04/2014 07:57 p.m., LeandroBraier wrote:

  > > Dale, porfa. Con eso estaríamos por el momento para ese
  backup. Gracias!

  > >

  > >

  > > 2014-04-22 19:31 GMT-03:00 mkreyness
  <notifications@github.com>:

  > >

  > > > Ok, entonces con copiar los HTML y las cosas que
  referencian (fotos y

  > > > unos pocos videos) alcanzaria.

  > > > Hay cosas que son programas (por ejemplo el
  Search), pero lo que traen

  > > > es el mismo contenido.

  > > > Te armo un .zip ?

  > > >

  > > >

  > > > On 22/04/2014 07:28 p.m., LeandroBraier wrote:

  > > > > Quieren los contenidos en sí, no hace falta el
  cms. Esto

  > > prácticamente

  > > > > implica las cargas de productos y recetas. Los
  demás lo bajo como

  > > HTML

  > > > > estimo.

  > > > >

  > > > >

  > > > > 2014-04-22 18:01 GMT-03:00 mkreyness
  <notifications@github.com>:

  > > > >

  > > > > > Es medio complicado porque comparten
  cosas.

  > > > > > Pero CMS de Danica tambien ? O sea, no
  entiendo si lo que

  > > quieren son

  > > > > > paginas estaticas o los programas que las
  producen, la base de

  > > > > datos, etc.

  > > > > >

  > > > > >

  > > > > > On 22/04/2014 05:28 p.m., LeandroBraier
  wrote:

  > > > > > > Es sin cabinas y sin
  "amamoscocinarconvos.com". Solo

  > > "danica.com.ar

  > > > ".

  > > > > > Eso

  > > > > > > es posible?

  > > > > > >

  > > > > > >

  > > > > > > 2014-04-22 17:10 GMT-03:00 mkreyness
  <notifications@github.com>:

  > > > > > >

  > > > > > > > Programas y base de datos
  incluidos ?

  > > > > > > > CMS ?

  > > > > > > > Videos te referis a los de las
  cabinas tambien ?

  > > > > > > >

  > > > > > > > No creo que tengamos lugar en
  el propio sitio para hacer una

  > > copia

  > > > > > > > comprimida de TODO, y
  levantarlo seria tambien hiperpesado.

  > > > > > > > Sin lo de cabinas, es mas
  manejable.

  > > > > > > >

  > > > > > > > On 22/04/2014 04:37 p.m.,
  LeandroBraier wrote:

  > > > > > > > >

  > > > > > > > > Marce, necesitaría un
  backup completo del sitio actual de

  > > > > Danica, con

  > > > > > > > > recetas, fotos, videos
  incluidos, etc, para pasarle al

  > > > > cliente. COmo

  > > > > > > > > te parece hacerlo?

  > > > > > > > >

  > > > > > > > > —

  > > > > > > > > Reply to this email
  directly or view it on GitHub

  > > > > > > > >
  <https://github.com/LeandroBraier/DanicaWeb/issues/20>.

  > > > > > > > >

  > > > > > > >

  > > > > > > > —

  > > > > > > > Reply to this email directly or
  view it on

  > > > > > > GitHub<

  > > > > >

  > > > >

  > > >

  > >

  >
```

https://github.com/LeandroBraier/DanicaWeb/issues/20#issuecomment-41089331
      > > > > > >

```
  > > > > >

  > > > > > > > .

  > > > > > > >

  > > > > > >

  > > > > > >

  > > > > > >

  > > > > > > --

  > > > > > > Leandro Braier

  > > > > > > Producción Audiovisual & Social
  Media

  > > > > > > Móvil 1158717399

  > > > > > >

  > > > > > > —

  > > > > > > Reply to this email directly or view
  it on GitHub

  > > > > > > <

  > > > > >

  > > > >

  > > >

  > >

  >
```

https://github.com/LeandroBraier/DanicaWeb/issues/20#issuecomment-41091498
      > > > > > >.

```
  > > > > >

  > > > > > >

  > > > > >

  > > > > > —

  > > > > > Reply to this email directly or view it
  on

  > > > > GitHub<

  > > >

  > >

  >
```

https://github.com/LeandroBraier/DanicaWeb/issues/20#issuecomment-41095224
      > > > >

```
  > > >

  > > > > > .

  > > > > >

  > > > >

  > > > >

  > > > >

  > > > > --

  > > > > Leandro Braier

  > > > > Producción Audiovisual & Social Media

  > > > > Benteveo Producciones
  <http://benteveo.tv>

  > > >

  > > > > Móvil 1158717399

  > > > >

  > > > > —

  > > > > Reply to this email directly or view it on
  GitHub

  > > > > <

  > > >

  > >

  >
```

https://github.com/LeandroBraier/DanicaWeb/issues/20#issuecomment-41103879
      > > > >.

```
  > > >

  > > > >

  > > >

  > > > —

  > > > Reply to this email directly or view it on

  > > GitHub<

  >
```

https://github.com/LeandroBraier/DanicaWeb/issues/20#issuecomment-41104135
      > >

```
  >

  > > > .

  > > >

  > >

  > >

  > >

  > > --

  > > Leandro Braier

  > > Producción Audiovisual & Social Media

  > > Benteveo Producciones <http://benteveo.tv>

  > > Móvil 1158717399

  > >

  > > —

  > > Reply to this email directly or view it on GitHub

  > > <

  >
```

https://github.com/LeandroBraier/DanicaWeb/issues/20#issuecomment-41106216
      > >.

```
  >

  > >

  >

  > —

  > Reply to this email directly or view it on
```

GitHubhttps://github.com/LeandroBraier/DanicaWeb/issues/20#issuecomment-41106458
      > .

```
  >

  -- 
  Leandro Braier

  Producción Audiovisual & Social Media

  Benteveo Producciones <http://benteveo.tv>

  Móvil 1158717399
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by LeandroBraier** [comment]
Gracias Marce!

Ya me lo descargué y está perfecto. Podés eliminarlo del FTP.
