### ISSUE TITLE
Acortador

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/DanicaWeb#21]
Marce, ¿habrá posibilidad de poner caracteres ilimitados al acortador?

**Comment by mkreyness** [comment]
Te referis al codigo o al url real?

Enviado desde mi iPhone

**Comment by LeandroBraier** [comment]
al código

On Thu, Apr 24, 2014 at 1:02 PM, mkreyness notifications@github.com wrote:

> Te referis al codigo o al url real?
> 
> Enviado desde mi iPhone
> 
> > El 24/04/2014, a las 12:26, LeandroBraier notifications@github.com
> > escribió:
> > 
> > Marce, ¿habrá posibilidad de poner caracteres ilimitados al acortador?
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/LeandroBraier/DanicaWeb/issues/21#issuecomment-41298175
> .

## 

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
Ilimitado no, porque es un campo clave.
Ahi le puse 255, que es el maximo que puedo ponerle a un campo que es 
clave. Deberia alcanzarte, si no, en que sentido seria un 'acortador' ? :)

**Comment by LeandroBraier** [comment]
jajaj gracias Marce!
