### ISSUE TITLE
Version 2.0: Preloader

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/DanicaWeb#23]
Eso, nos falta un preloader de Dánica para las 2 webs, pero especialmente para la de Dánica principal. Nos sugerís algunos diseños Fede?

**Comment by FAAREIA** [comment]
Mmmmmm, no se en que parte pondría un preloader Lea.
¿Qué pantallas pensas que son bien pesadas y tardan en cargar?

También hay preloader dinámico, esto implica que a medida que bajas en el sitio, se van cargan las imágenes por ejemplo. Lo mismo que hace facebook cuando bajas y bajas.
Igualmente, lo aplicaría a casos que lo requieren y no donde hay 20 imágenes chicas nomas.

**Comment by mkreyness** [comment]
supongo q se refiere a la galeria de thumbnails del concurso.

**Comment by LeandroBraier** [comment]
No exclusivamente. Pensemos que se conecta gente con conexiones a internet y maquinas muy distintaa. Por las dudas lo pondría. O uno diseñado uno dinámico como el que decis. El que te parezca mejor de acuerdo a la página.

**Comment by FAAREIA** [comment]
El tema Lea es que esto no es flash. El preloader, según tengo entendido, sirve para precargar imágenes o videos pero no para precargar un HTML, o un javascript o css. Estás suelen ser livianas, y en nuestro proyecto lo son. De hecho, el css carga imágenes también, eso no se puede precargar.
La version para celulares es más liviana porque lleva menos elementos.
Si hay un lugar que lo pondría es la galería del concurso como dijo marce, en otro no lo veo necesario.

**Comment by LeandroBraier** [comment]
Ok, me parece bien entonces. Hagamos uno para la galería del concurso que
tenga que ver con la estética misma del Concurso. ¿Qué imagen se te ocurre?
Tendría que ser algo bien visual y simple.

2014-04-28 11:14 GMT-03:00 Federico Arena notifications@github.com:

> El tema Lea es que esto no es flash. El preloader, según tengo entendido,
> sirve para precargar imágenes o videos pero no para precargar un HTML, o un
> javascript o css. Estás suelen ser livianas, y en nuestro proyecto lo son.
> De hecho, el css carga imágenes también, eso no se puede precargar.
> La version para celulares es más liviana porque lleva menos elementos.
> Si hay un lugar que lo pondría es la galería del concurso como dijo marce,
> en otro no lo veo necesario.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/LeandroBraier/DanicaWeb/issues/23#issuecomment-41562812
> .

## 

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Haría un preloader dinámico, pondría algo simple que va girando, lo estandar en un preloader. Tendría que ser un gif, que máximo soporta 256 colores.
Pensá también que aparecería solamente cuando carga imágenes que aún no viste desde la pantalla.

**Comment by LeandroBraier** [comment]
Perfecto.

2014-04-28 11:22 GMT-03:00 Federico Arena notifications@github.com:

> Haría un preloader dinámico, pondría algo simple que va girando, lo
> estandar en un preloader. Tendría que ser un gif, que máximo soporta 256
> colores.
> Pensá también que aparecería solamente cuando carga imágenes que aún no
> viste desde la pantalla.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/LeandroBraier/DanicaWeb/issues/23#issuecomment-41563801
> .

## 

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Vayamos con eso y vemos como funciona. Si queda muy estándar pensamos algo
más relacionado con la comida y con Dánica.

2014-04-28 11:36 GMT-03:00 Leandro Braier leandrobraier@gmail.com:

> Perfecto.
> 
> 2014-04-28 11:22 GMT-03:00 Federico Arena notifications@github.com:
> 
> Haría un preloader dinámico, pondría algo simple que va girando, lo
> 
> > estandar en un preloader. Tendría que ser un gif, que máximo soporta 256
> > colores.
> > Pensá también que aparecería solamente cuando carga imágenes que aún no
> > viste desde la pantalla.
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/LeandroBraier/DanicaWeb/issues/23#issuecomment-41563801
> > .
> 
> ## 
> 
> Leandro Braier
> Producción Audiovisual & Social Media
> Benteveo Producciones http://benteveo.tv
> Móvil 1158717399

## 

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Ya esta implementado el loader dinámico.
http://amamoscocinarconvos.com/cgi-bin/galeria.pl
El tema de poner un gif animado, es que va a ser ruido con la imagen que marca si es video o foto. Creo que igual no hace falta, fijense y me dicen.

**Comment by LeandroBraier** [comment]
La verdad, no lo logro ver. Será que tengo el wifi muy rápido? jeje

2014-04-28 12:04 GMT-03:00 Federico Arena notifications@github.com:

> Ya esta implementado el loader dinámico.
> http://amamoscocinarconvos.com/cgi-bin/galeria.pl
> El tema de poner un gif animado, es que va a ser ruido con la imagen que
> marca si es video o foto. Creo que igual no hace falta, fijense y me dicen.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/LeandroBraier/DanicaWeb/issues/23#issuecomment-41569164
> .

## 

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Dale ctrl+F5 que lo tenes cacheado seguro.

**Comment by FAAREIA** [comment]
Cierren el issue si les parece que esta OK

**Comment by LeandroBraier** [comment]
Está OK!
