### ISSUE TITLE
Version 2.0: Convertidor con mouse over

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/DanicaWeb#24]
Marce, ¿te acordás del convertidor de unidades?

Con Marce S decimos de agregarlo en la receta de alguna forma que, al hacer mouseover sobre la unidad, te diga su equivalente en las otras unidades (cm3, cucharadas, etc). ¿Cómo lo ves?

**Comment by mkreyness** [comment]
Lo que no tenemos actualmente es una tabla de unidades, tendriamos que 
cargar una tabla con las equivalencias asi el programa puede generar 
automaticamente los mouseovers. No es nada dificil.

**Comment by LeandroBraier** [comment]
Perfecto. Lo ideal sería que te pase la tabla de equivalencias y listo no?

2014-04-25 18:00 GMT-03:00 mkreyness notifications@github.com:

> Lo que no tenemos actualmente es una tabla de unidades, tendriamos que
> cargar una tabla con las equivalencias asi el programa puede generar
> automaticamente los mouseovers. No es nada dificil.
> 
> On 25/04/2014 05:50 p.m., LeandroBraier wrote:
> 
> > Marce, ¿te acordás del convertidor de unidades?
> > 
> > Con Marce S decimos de agregarlo en la receta de alguna forma que, al
> > hacer mouseover sobre la unidad, te diga su equivalente en las otras
> > unidades (cm3, cucharadas, etc). ¿Cómo lo ves?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/LeandroBraier/DanicaWeb/issues/24.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/LeandroBraier/DanicaWeb/issues/24#issuecomment-41438851
> .

## 

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
Si, pero si el dia de mañana se agrega algun nuevo tipo de unidades, 
seria mejor que este directamente como una tabla en el CMS y lo puedas 
agregar.

**Comment by LeandroBraier** [comment]
Perfecto, avanzá con la tabla del CMS y avisame cuando puedo subir las
equivalencias entonces. No hay tanto apuro con esto.

abrazo

2014-04-25 18:15 GMT-03:00 mkreyness notifications@github.com:

> Si, pero si el dia de mañana se agrega algun nuevo tipo de unidades,
> seria mejor que este directamente como una tabla en el CMS y lo puedas
> agregar.
> 
> On 25/04/2014 06:13 p.m., LeandroBraier wrote:
> 
> > Perfecto. Lo ideal sería que te pase la tabla de equivalencias y listo
> > no?
> > 
> > 2014-04-25 18:00 GMT-03:00 mkreyness notifications@github.com:
> > 
> > > Lo que no tenemos actualmente es una tabla de unidades, tendriamos que
> > > cargar una tabla con las equivalencias asi el programa puede generar
> > > automaticamente los mouseovers. No es nada dificil.
> > > 
> > > On 25/04/2014 05:50 p.m., LeandroBraier wrote:
> > > 
> > > > Marce, ¿te acordás del convertidor de unidades?
> > > > 
> > > > Con Marce S decimos de agregarlo en la receta de alguna forma que, al
> > > > hacer mouseover sobre la unidad, te diga su equivalente en las otras
> > > > unidades (cm3, cucharadas, etc). ¿Cómo lo ves?
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > https://github.com/LeandroBraier/DanicaWeb/issues/24.
> > > 
> > > —
> > > Reply to this email directly or view it on
> > > GitHub<
> > > https://github.com/LeandroBraier/DanicaWeb/issues/24#issuecomment-41438851
> > > 
> > > .
> > 
> > ## 
> > 
> > Leandro Braier
> > Producción Audiovisual & Social Media
> > Benteveo Producciones http://benteveo.tv
> > Móvil 1158717399
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/LeandroBraier/DanicaWeb/issues/24#issuecomment-41440046
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/LeandroBraier/DanicaWeb/issues/24#issuecomment-41440179
> .

## 

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Marce, avisame cuando puedo subir las tablas de equivalencias.

abrazo

**Comment by LeandroBraier** [comment]
Esto está en stand by MK?

**Comment by mkreyness** [comment]
```
Como cualquier cosa que sea version 2.0, si.El 19/05/2014 20:30, LeandroBraier
  escribió:

  Esto está en stand by MK?
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by LeandroBraier** [comment]
Esto lo saco de encima, Marce. abrazo
