### ISSUE TITLE
Resolver el tema DNS en duplika asi se puede dar de baja UO

### ISSUE THREAD

**Issue by marcsuse** [LeandroBraier/DanicaWeb#25]
http://www.intodns.com/danica.com.ar

**Comment by FAAREIA** [comment]
Hola Marce, voy a preguntar al respecto. Realmente no estoy muy informado sobre tema DNS, simplemente suelo asignarlos y listo.

**Comment by FAAREIA** [comment]
¿Cuál es la función de UO solutions y porque inicialmente no funcionó con los DNS de Duplika?
¿El dominio de danica.com.ar esta en nic.ar?

**Comment by FAAREIA** [comment]
Hola Marce, ¿me pasarías por mail los accesos a nic.ar para sacar uosolutions de los dns? Estuve hablando con Marce K y me comentó que esos dns ya no se usan, que estaban antes del sitio que hicimos.
Gracias.

**Comment by marcsuse** [comment]
Fede, No se pueden sacar los dns de UO porque aun no responden correctamente los de duplica:

ERROR: One or more of your nameservers did not respond:
The ones that did not respond are:
190.228.29.45 50.28.56.141 190.210.180.100

Podes verlo aca: http://www.intodns.com/danica.com.ar

Entiendo que ellos deberían cargar el A record

danica.com.ar.      1731    IN  A   209.59.169.204

**Comment by FAAREIA** [comment]
Hola Marce, le escribí a Juan el de Duplika y me dijo lo siguiente. ¿El
domino servidoronline sigue usandose?

---

Hola Federico,
¿El dominio danica.com.ar debería apuntar al plan Onyx contrado con el
dominio danica.servidoronline.net?

Si es asi, podrías escribirnos desde la cuenta titular del plan para que
realicemos el cambio de dominio?

Saludos,

---

**Comment by mkreyness** [comment]
Si, danica.servidoronline.net no se usa para nada.
Pero ojo que amamoscocinarconvos.com tambien esta asociada a la misma 
cuenta de duplika.
No sea cosa que deje de andar por este cambio.

**Comment by FAAREIA** [comment]
Lo que entiendo yo es que Juan va a apuntar danica.com.ar al plan onyx, si
el que contrató el plan le manda un mail pidiendoselo. ¿Esta bien? ¿Donde
esta apuntando danica.com.ar ahora?

**Comment by mkreyness** [comment]
No se lo que quieren decir con apuntar un dominio A UN PLAN.
El plan es una cuestion comercial, sera que el plan puede tener un unico 
domain OFICIALMENTE, pero la verdad que hace rato que tanto 
danica.com.ar como amamoscocinarconvos.com apuntan al mismo IP que 
danica.servidoronline.net.
TAL VEZ el plan que se contrató no permite tener mas de un domain, y 
ellos creen que ese domain (que no es un domain, es un subdomain) es 
danica.servidoronline.net.
No se, habria que ver cuantos domains se banca "un plan Onyx".

**Comment by FAAREIA** [comment]
Le pregunté a Juan, vamos a ver que dice.

**Comment by FAAREIA** [comment]
Bueno, estas son las palabras de Juan:

---

```
En http://www.intodns.com/danica.com.ar hay 2 errores:

Efectivamente, debería estar delegado solo a nuestros DNS.
Nuestros DNS no confirman la zona ya que la misma no esta creada. Para hacerlo deberíamos cambiar el dominio del plan o agregar danica.com.ar como dominio apuntado desde el cPanel.
```

---

Lo que se puede hacer facilmente es agregar danica.com.ar como dominio apuntado desde el cpanel. Según sé, el dominio apunta a X plan de hosting, pero si ese dominio no es el del hosting o no esta permitido (no esta en la lista de dominios apuntados), lo rechaza.

Lo agrego ahora mismo y al mediodía nos fijamos si tira el mismo error en intodns.

Abrazo

**Comment by FAAREIA** [comment]
Ya lo agregué, lo voy a ir chequeando todo el tiempo a ver si sigue todo como siempre.

**Comment by FAAREIA** [comment]
Bueno, volviendo al tema.
http://www.intodns.com/danica.com.ar
Parece que da solo error ahora en uo ya que no estan parked / apuntados desde el cpanel.
¿Sacamos UO de nic.ar?

**Comment by mkreyness** [comment]
Si, hay que sacarlos porque ya no son "autoritativos".

**Comment by FAAREIA** [comment]
El que pueda los saca, sino pasen usuario y clave por mail y lo hago.

**Comment by mkreyness** [comment]
Ni idea.

**Comment by marcsuse** [comment]
Yo me ocupo

**Comment by LeandroBraier** [comment]
Avisen si esto quedó resuelto cuando puedan.
abrazo

**Comment by LeandroBraier** [comment]
Marce, avisame si esto quedó resuelto porfa. abrazo

**Comment by mkreyness** [comment]
```
De cual dominio estamos hablando, solamente danica.com.ar ?
Segun Nic.ar esta full apuntando a duplika, nada en UO.

El 04/11/2014 a las 20:36,
  LeandroBraier escribió:


  Marce, avisame si esto quedó resuelto porfa. abrazo
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by LeandroBraier** [comment]
genial!
