### ISSUE TITLE
Sin Links al Hacer Back en el buscador

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/DanicaWeb#26]
Te comento el pequeño issue (no prioritario)

1) Hago una búsqueda en el sitio

2) Veo los resultados

3) Clic en un resultado

4) Hago back

5) Los resultados no son linkeable ANYMORE

Avisame cuando sepas por qué ocurre esto o si te parece que se lo pasamos a MK

abrazo

**Comment by mkreyness** [comment]
No tiene que ver con el buscador en si.
Pasa lo mismo si haces click en cualquier receta de una categoria.
Los links estan, pero como que no podes clickearlos.
Es algo del boton "Compartir" que se queda medio como colgado (fijate 
que no aparece, y arriba sigue cargando la pagina).
Si esperas un poco a que aparezca, vas a ver que se libera todo y sigue 
andando.

**Comment by LeandroBraier** [comment]
OK, gracias!

**Comment by LeandroBraier** [comment]
No se soluciona esperando. Estoy con el Chrome Versión 34.0.1847.131.

**Comment by mkreyness** [comment]
Pero te aparece bien el boton de "compartir"? Porque lo que yo vi q mientras el boton no esta o aparece medio tapado por el boton de pinterest, ningun link de nada funciona, está colgada la carga de la página. Solo zafas haciendo reload.

Enviado desde mi iPhone

**Comment by LeandroBraier** [comment]
Claro, es eso. Como lo podemos resolver?

2014-05-16 15:41 GMT-03:00 mkreyness notifications@github.com:

> Pero te aparece bien el boton de "compartir"? Porque lo que yo vi q
> mientras el boton no esta o aparece medio tapado por el boton de pinterest,
> ningun link de nada funciona, está colgada la carga de la página. Solo
> zafas haciendo reload.
> 
> Enviado desde mi iPhone
> 
> > El 16/05/2014, a las 15:10, LeandroBraier notifications@github.com
> > escribió:
> > 
> > No se soluciona esperando. Estoy con el Chrome Versión 34.0.1847.131.
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/LeandroBraier/DanicaWeb/issues/26#issuecomment-43365461
> .

## 

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
No no, eso no se resuelve. Si tarda es porque el pedido y el envío de datos hacia y desde FB tarda. Es común que no aparezca al instante porque no es tu servidor, sino el de otro.

**Comment by LeandroBraier** [comment]
Ok, pero como se puede mitigar el tema? A mi no me vuelve nunca a cargar después. No es que espero y aparece.

**Comment by FAAREIA** [comment]
Mmmmmmmm, nunca lo había escuchado. Debes ser vos, probaste desde otra maquina? Sin estar logueado al FB? Estando logueado?

**Comment by mkreyness** [comment]
A mi tambien me pasa. Hago reload y se arregla.
Lo que veo es que los iconos de "me gusta" y "compartir" no aparecen.

**Comment by FAAREIA** [comment]
Habría que rastrearlo para saber que sucede realmente. Lo que si sabemos es que el código lo provee FB y la ida y vuelta de datos depende más de ellos que de nosotros. Debe ser un bug de ellos por x motivo

**Comment by LeandroBraier** [comment]
Entonces veamos qué podemos sacar del plugin de facebook para que este no
pase. Si hay que sacar el botón compartir saquemoslo.

2014-05-17 10:59 GMT-03:00 Federico Arena notifications@github.com:

> Habría que rastrearlo para saber que sucede realmente. Lo que si sabemos
> es que el código lo provee FB y la ida y vuelta de datos depende más de
> ellos que de nosotros. Debe ser un bug de ellos por x motivo
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/LeandroBraier/DanicaWeb/issues/26#issuecomment-43407560
> .

## 

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
O mejor: busquemos otro plugin de "compartir" de Facebook, no?

2014-05-17 11:03 GMT-03:00 Leandro Braier leandrobraier@gmail.com:

> Entonces veamos qué podemos sacar del plugin de facebook para que este no
> pase. Si hay que sacar el botón compartir saquemoslo.
> 
> 2014-05-17 10:59 GMT-03:00 Federico Arena notifications@github.com:
> 
> Habría que rastrearlo para saber que sucede realmente. Lo que si sabemos
> 
> > es que el código lo provee FB y la ida y vuelta de datos depende más de
> > ellos que de nosotros. Debe ser un bug de ellos por x motivo
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/LeandroBraier/DanicaWeb/issues/26#issuecomment-43407560
> > .
> 
> ## 
> 
> Leandro Braier
> Producción Audiovisual & Social Media
> Benteveo Producciones http://benteveo.tv
> Móvil 1158717399

## 

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
El boton de compartir es solo 1, no hay variables de una misma funcion en fb segun sé.
Sacarlo, no lo sacaría, no rompe el sitio ni genera nada raro. Simplemente el que le apreta "atras", no lo verá. En mi caso, hoy, ahora, lo veo siempre que le doy atras. Carga bien.

**Comment by mkreyness** [comment]
no tiene que ver en si con dar "atras", puede pasar en cualquier momento.

**Comment by FAAREIA** [comment]
A mi nunca me dejó de andar entonces, no es instantaneo como Twitter, pero entiendo que la data mostrada no esta en nuestra base de datos.

**Comment by LeandroBraier** [comment]
Ya se. No le podemos poner que cuando alguien haga "back" haga refresh automatico?

**Comment by FAAREIA** [comment]
Sería raro, podría resultar molesto o un error. No daría mucha vuelta con esto. Esos botones no son información importante, son botones que se clickean 1 vez y se ven 1 vez y listo. No es algo vital.
Por mi parte, reitero, siempre los vi bien. Hoy, ahora, también.

**Comment by LeandroBraier** [comment]
El tema es que haces back y no anda NINGUN link. Los botones vaya y pase.

**Comment by FAAREIA** [comment]
Es raro, a mi me anda bien en todos los navegadores. Pensá que logicamente volves a lo que antes había, lo cual funcionaba, ni idea que te puede estar pasando en el medio.
Deshabilita los plugins que tengas para probar.

**Comment by mkreyness** [comment]
Yo aunque me anden los links veo que se pone loco el icono de reload, 
como que parpadea todo el tiempo.
El error que veo en el debugger dice esto, habria que ver si se puede 
hacer que acceda a facebook con http en vez de https:

Blocked a frame with origin "https://www.facebook.com 
https://www.facebook.com/" from accessing a frame with origin 
"http://www.danica.com.ar http://www.danica.com.ar/". The frame 
requesting access has a protocol of "https", the frame being accessed 
has a protocol of "about". Protocols must match.

**Comment by LeandroBraier** [comment]
Pero a Marce K le pasaba lo mismo.

**Comment by mkreyness** [comment]
Y me sigue pasando. Es cierto que es mucho mas facil de reproducir 
haciendo back.
Proba esto Fede:
entras en una categoria cualquiera, por ejemplo "Dulce Dulcisimo".
Haces click en la primer receta (Delicia de Durazno) y apretas back 
INMEDIATAMENTE.
Vuelve a la pagina anterior, pero se queda 45 segundos colgados, y 
despues en el debugger (console de Chrome) dice:

fb:like failed to resize in 45s
fb:activity failed to resize in 45s

Antes de eso se veian pero pisados por los otros iconos.
Despues de dar estos errores, directamente desaparecieron.
Ahi si empiezan a andar los links, antes de eso no, obviamente porque 
esta colgado esperando esos 45 segundos.

**Comment by LeandroBraier** [comment]
No podemos evitar que Chrome tenga que hacer resize de esos botones? Es decir, que cuando alguien haga back, los botones de like y activity de Facebook queden más grandes y listo?

**Comment by FAAREIA** [comment]
Ahora si lo pude reproducir, pero solo en Chrome.
FF e IE andan bien siempre. Es sólo un error de Chrome o webkit en general.

http://stackoverflow.com/questions/16833196/fblogin-button-failed-to-resize-in-45s
Capas que la tercer respuesta o probar algo de ahi puede funcionar. No encontré mucho

**Comment by mkreyness** [comment]
Hacer esto decis ?

|#fb_login_button {
     width:  80px;  
}
#fb_login_button span,
#fb_login_button iframe {.
     width:  80px!  important;
     height:  25px!  important;
}

|
|

Lo tendrias que probar tocando en el CSS, no ?

**Comment by FAAREIA** [comment]
No, digo la tercer respuesta, sin contar la pregunta.
Eso puede funcionar para visualizar el botón, habría que probarlo, pero el tema es que el error te bugea la página y no anda ningun link.

**Comment by mkreyness** [comment]
esa es la que yo veo como tercera...
Cual decis vos ?

**Comment by FAAREIA** [comment]
Digo la que dice:

> I have the same problem. I was getting fb:post failed to resize in 45s.
> 
> Because I did not provide my Facebook app website URL. So go to your Facebook app settings >and type your URL like this:

Ahora agrego lo del CSS para probar

**Comment by FAAREIA** [comment]
Solucionado. El código que pone el tipo ese ayuda a mostrar el botón, pero no fuerza la caja. Ésto me llevo a investigar un poco más, y el error parece que dispara un div, sin nada, que lo pone por encima de todo (un position:absolute con z-index). Simplemente le di al contenedor un position: relative, overflow: hidden, y listo!. Denle F5, pruebenlo y cualquier cosa se reabre.

PD: En la consola sigue apareciendo el error

**Comment by LeandroBraier** [comment]
Buenísimo Fede! Gracias! Yo sabía que algo se podía hacer.

PD: Qué es la consola?

**Comment by FAAREIA** [comment]
La consola es como el rastreo de errores de una página, es una solapa en las herramientas de desarrollo

**Comment by mkreyness** [comment]
```
Genial.
Respecto de lo de poner el Site URL en el app de facebook, siempre
estuvo puesto desde el primer dia, si no da todo tipo de otros
errores adicionales.El 19/05/2014 21:44, Federico Arena
  escribió:

  La consola es como el rastreo de errores de una página, es una
    solapa en las herramientas de desarrollo
  —
    Reply to this email directly or view
      it on GitHub.
```
