### ISSUE TITLE
Supuesto error en Formulario Web

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/DanicaWeb#27]
MK, te paso un mensaje de un usuario en Twitter. Decime si significa algo para vos, para mi es chino.

"Nos reporta en varios tweets (cortados) que cuando quiere ingresar los datos del formulario (lo probé y tiene razón) redirecciona a este sitio ""http://danica.com.ar/danica/template/php/mail.php"" que tiene este contenido en texto ""
Deprecated: Function set_magic_quotes_runtime() is deprecated in /home/danicase/public_html/danica/template/php/mail.php on line 50

Warning: Cannot modify header information - headers already sent by (output started at /home/danicase/public_html/danica/template/php/mail.php:50) in /home/danicase/public_html/danica/template/php/mail.php on line 136"""

**Comment by mkreyness** [comment]
Hay algun link malo, pero no entiendo donde, parece algo asi como un contact form ? No se donde estan queriendo entrar.

Enviado desde mi iPhone

**Comment by LeandroBraier** [comment]
Por las dudas no le respondo.

2014-05-13 15:33 GMT-03:00 mkreyness notifications@github.com:

> Hay algun link malo, pero no entiendo donde, parece algo asi como un
> contact form ? No se donde estan queriendo entrar.
> 
> Enviado desde mi iPhone
> 
> > El 13/05/2014, a las 15:23, LeandroBraier notifications@github.com
> > escribió:
> > 
> > MK, te paso un mensaje de un usuario en Twitter. Decime si significa
> > algo para vos, para mi es chino.
> > 
> > "Nos reporta en varios tweets (cortados) que cuando quiere ingresar los
> > datos del formulario (lo probé y tiene razón) redirecciona a este sitio ""
> > http://danica.com.ar/danica/template/php/mail.php"" que tiene este
> > contenido en texto ""
> > Deprecated: Function set_magic_quotes_runtime() is deprecated in
> > /home/danicase/public_html/danica/template/php/mail.php on line 50
> > 
> > Warning: Cannot modify header information - headers already sent by
> > (output started at
> > /home/danicase/public_html/danica/template/php/mail.php:50) in
> > /home/danicase/public_html/danica/template/php/mail.php on line 136"""
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/LeandroBraier/DanicaWeb/issues/27#issuecomment-42994102
> .

## 

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by marcsuse** [comment]
Esto parece ser en el form de contacto.

**Comment by mkreyness** [comment]
Si, da ese error.
Le saque esa linea que dice "deprecated" y listo, ya lo probe y mande un 
mail de contacto.
Habran cambiado la version del php, antes andaba bien.

**Comment by LeandroBraier** [comment]
Genial, gracias MK y MS!

**Comment by LeandroBraier** [comment]
Vuelve el supuesto error. a nuestro CM le pasa lo mismo:

http://danica.com.ar/danica/template/php/mail.php

La versión de Chrome es Versión 34.0.1847.131 m

**Comment by mkreyness** [comment]
Con ese link no puedo determinar nada, ya que no tendria que llamarselo 
asi suelto.
Desde donde le pasó, en la home ? Y cargando que datos en el form ?
Porque yo lo uso sobre el que esta en la home, pongo mis datos, y no me 
da ningun error.
Fijate que deberia llegarte mi mensaje de testing a la casilla 
correspondiente.
No deberia tener que ver con el browser tampoco, ya que es un script en 
el servidor.

**Comment by LeandroBraier** [comment]
Marce, te paso el mensaje que nos envió este pseudo hacker buena onda en varios tweets. El formulario es el de "Somos Danica".

Cuando quiero ingresar los datos del formulario redirecciona a este sitio "http://danica.com.ar/danica/template/php/mail.php" que tiene este contenido en texto "
Deprecated: Function set_magic_quotes_runtime() is deprecated in /home/danicase/public_html/danica/template/php/mail.php on line 50

Warning: Cannot modify header information - headers already sent by (output started at /home/danicase/public_html/danica/template/php/mail.php:50) in /home/danicase/public_html/danica/template/php/mail.php on line 136"   

A nuestro CM le ocurre lo mismo con el Chrome versión que te pasé.

**Comment by mkreyness** [comment]
```
Ok, pero es viejo eso, ya lo arregle apenas lo dijeron hace tiempo,
esa linea de codigo no existe mas, no puede estar dando AHORA. 
Cuando lo dijeron lo pude reproducir, le saque esa linea, e
inmediatamente dejo de dar el error.
Ademas no hay forma de que haya una cuestion de "cacheo" porque esto
corre en el servidor, no en el browser, el browser no tiene ninguna
incidencia.El 17/05/2014 18:22, LeandroBraier
  escribió:

  Marce, te paso el mensaje que nos envió este pseudo hacker
    buena onda en varios tweets. El formulario es el de "Somos
    Danica".
  Cuando quiero ingresar los datos del formulario redirecciona a
    este sitio "http://danica.com.ar/danica/template/php/mail.php"
    que tiene este contenido en texto "
    Deprecated: Function set_magic_quotes_runtime() is deprecated in
    /home/danicase/public_html/danica/template/php/mail.php on line
    50
  Warning: Cannot modify header information - headers already
    sent by (output started at
    /home/danicase/public_html/danica/template/php/mail.php:50) in
    /home/danicase/public_html/danica/template/php/mail.php on line
    136" 
  A nuestro CM le ocurre lo mismo con el Chrome versión que te
    pasé.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by LeandroBraier** [comment]
Resuelto!

Está confirmado por el CM. Gracias MK!
