### ISSUE TITLE
Página Asistente Dánica

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/DanicaWeb#3]
Necesito que ya diseñes la página del asistente dánica. Sigue la misma estética de antes pero va a llevar un logo propio de Asistente Dánica (que te lo voy a mandar yo). Mientras tanto, te paso el PSD por mail para que lo vayas maquetando. Lo necesito para el viernes si es posible.

abrazo

**Comment by LeandroBraier** [comment]
Corregí el diseño en caso de ser necesario, el PSD es a modo de referencia funcional. Estéticamente debería quedar mucho más lindo que eso, es página ES el Asistente Dánica en sí mismo.

**Comment by FAAREIA** [comment]
Oka, espero el logo y mientras veo como mejorar un poco esto.

**Comment by LeandroBraier** [comment]
El logo lo está diseñando Benkei, pero te subí a la carpeta la referencia que yo le mandé para que tengas como provisoria. De hecho, si vos la mejorás y queda linda, ya queda final. abrazo

**Comment by LeandroBraier** [comment]
Cómo venís con esto? llegamos para mañana?

**Comment by FAAREIA** [comment]
Hoy me pongo con eso Lea, el form ahi en el medio no lo voy a dejar igual. Llegamos tranquilos.
Abrazo

**Comment by FAAREIA** [comment]
Lea, el icono del asistente es: Logo Asistente Danica.psd ?

**Comment by LeandroBraier** [comment]
te acabo de subir una carpeta con el logo que va. Quizá le hacemos algun cambio pequeño más, pero es el que va. Está en la carpeta BOTON ASISTENTE. Olvidate del "logo asistente danica.psd" abrazo

**Comment by FAAREIA** [comment]
Ok, igual estoy medio confudido.
El diseño de la página de Asistencia, cambia por el diseño en "asistente-danicaOk.psd"
Lo del botón va al costado del formulario del nuevo diseño?

**Comment by LeandroBraier** [comment]
No. En el psd de boton tenes el logo del asistente. Lo demas en el psd ignoralo. Usa el boton como logo del asistente.

**Comment by FAAREIA** [comment]
![sin-ttulo-1](https://f.cloud.github.com/assets/6184969/2221556/74765d6a-9a5a-11e3-81f7-7cf2cff54df3.jpg)
Ese es no?
Digo para no mandarme ninguna cagada

**Comment by LeandroBraier** [comment]
Si, ese. El único tema es que para la home vamos a tener que adaptarlo porque ahí no queda tan bien, no?

**Comment by FAAREIA** [comment]
Una version horizontal quedaría mejor supongo

**Comment by LeandroBraier** [comment]
che, no encuentro la página en el dropbox, donde la subistE?

**Comment by LeandroBraier** [comment]
Fede, tres cositas nomás:
1. Falta la S de ¿PREPARÁS PLATOS ELABORADOS?
2. Destacá un poco más el logo. puede ser un sombreado negro o algo así.
3. Subime porfa el PSD a tu dropbox ya que lo necesito para la aplicación.

abrazo

**Comment by LeandroBraier** [comment]
Fede, tengo más pedidos de cambios que me pasó Marce S por mail.
1. En la opción "Cuántos son en tu casa" poner lista desplegable de 1 a 12.
2. Agregar una opción también con lista desplegable: ¿Qué días querés recibir sugerencias?

LUNES, MARTES, MIERCOLES, JUEVES, VIERNES, SABADO, DOMINGO.
1. Agregar una opción también con lista desplegable: ¿A qué hora querés recibir las sugerencias? 00 a 24 hs.

**Comment by LeandroBraier** [comment]
Además, actualizale el logo del Asistente Dánica, ya que hay uno que con pequeñas nuevas modificaciones. El link de descarga es este:

https://www.dropbox.com/s/8infadzcnkwmrhp/Logo%20Asistente%20DanicaOK.psd

**Comment by FAAREIA** [comment]
Ahi estan las actualizaciones. Le aviso a marce

**Comment by LeandroBraier** [comment]
Gracias Fede, lo que necesito sí o si cuanto antes es el PSD de esta página porfa.

abrazo

**Comment by FAAREIA** [comment]
http://danica.com.ar/asistente-danicaOk.zip

**Comment by LeandroBraier** [comment]
Gracias. Benkei ya lo está armando para la aplicación. Si querés te lo paso cuando lo terminé así podemos aplicar algo de ese diseño en la web. abrazo

**Comment by LeandroBraier** [comment]
Ya te lo subí a tu dropbox en la carpeta Asistente Dánica/ Asistente final, lo viste?

**Comment by FAAREIA** [comment]
Ahi lo vi lea, em pongo con eso

**Comment by FAAREIA** [comment]
Ya esta subido el asistente, falta el icono horizontal para el header.

**Comment by LeandroBraier** [comment]
Buen día Fede! Te mandé via mail también la consulta. El asistente-danica33.html es la versión ya modificada? En tal caso hacele un chequeo de distintos navegadores. En el firefox 27.0.1 no me lee el formato. abrazo

**Comment by LeandroBraier** [comment]
Todo aclarado! Te adjunté via mail y en dropbox los nuevos íconos que te faltan para cerdo y vegetariano. El de carne vacuna usá el de "carne" que ya tenés en ingredientes y para el resto dejá los que están. abrazo

**Comment by FAAREIA** [comment]
Hola Lea, ahi ya estan puestos!
abrazo

**Comment by LeandroBraier** [comment]
Perfecto, gracias! Es idea mia o están desalineados los días de la semana? Puede ser?

**Comment by FAAREIA** [comment]
Los puse alineados, capas que la "J" te da esa sensación.

**Comment by LeandroBraier** [comment]
Ok, perfecto, era una sensación. Solo te pido unos cambios de ortografía:

"Queres que te enviemos recetas con (elegí una o mas opciones):" (falta el tilde en Querés)

"¿Tenes chicos?" (falta el tilde en Tenés)

"¿Cuantos son en tu casa?" (falta el tilde en Cuántos)

**Comment by FAAREIA** [comment]
Ahora que me acuerdo, Marce S quería buscar una frase mejor para "Queres que te enviemos recetas con (elegí una o mas opciones)". Si podes consultale a ver si queda esa o pensó una nueva.

**Comment by LeandroBraier** [comment]
Dale, lo veo con él. Mientras tanto agregale los tildes por las dudas.

**Comment by FAAREIA** [comment]
Prefiero hacer todo junto Lea, ahora estoy tratando de montar una maquina virtual asi tengo OS X en mi PC y puedo probar lo que ustedes ven.
Abrazo

**Comment by LeandroBraier** [comment]
Confirmado Fede. El texto actual es el definitivo Agregale todas las tildes que faltan y agrega la opcion que dice MK, que hasta que no estén llenas todas las opciones no se habilite el boton de activar.

**Comment by mkreyness** [comment]
Ahi le agregue yo las validaciones, fijense si les anda bien, lo que 
hace es mostrar un unico cartel con todos los problemas, pero la letra 
negra sobre fondo rojo para mi no se ve bien, lo pondria con letra 
blanca (lo deje asi como esta para ser coherente con los otros mensajes 
de rechazo).

Tampoco estoy seguro de que el mail que esta mandando tiene todo, 
Leandro forwardeame lo que te llegó a danica_ast asi verifico que tenga 
todo lo que marqué. Gracias.

**Comment by FAAREIA** [comment]
Reabrir si es necesario
