### ISSUE TITLE
Modificación o Desactivación Asistente con mensaje "UNKNOWN"

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/DanicaWeb#30]
Marce, estoy teniendo problemas con el Asistente Dánica en versión Web. Te cuento el proceso:
1. En el mailing del Asistente, hago clic en el botón de abajo de todo "Haga clic aquí"
2. Llego a mi página con mis settings del Asistente correctamente.
3. Primer error: solo me aparece el nombre, no el apellido.
4. Corrijo los settings y hago clic en "Actualizar datos". Me aparece un pop up con el mensaje "DANICA. Unknown". Cierro el mensaje y me lleva a la home de Dánica.
5. Intento nuevamente haciendo clic en "Desactivar el asistente". Nuevamente me aparece un pop up con el mensaje "DANICA. Unknown". Cierro el mensaje y me lleva a la home de Dánica.

¿Qué puede estar ocurriendo?

**Comment by mkreyness** [comment]
```
Es un usuario que creaste desde el App ?
Dame cual es el usuario y pruebo. Ya sabemos que el App tiene un
solo campo que se llama "name", esto le pasaron mal la definicion de
las pantallas a los hindues y quedó siempre asi, cuando te registras
con facebook solo toman el dato "nombre" y nunca el Apellido.El 04/06/2014 9:42, LeandroBraier
  escribió:

  Marce, estoy teniendo problemas con el Asistente Dánica en
    versión Web. Te cuento el proceso:
  En el mailing del Asistente, hago clic en el botón de abajo
      de todo "Haga clic aquí"
    Llego a mi página con mis settings del Asistente
      correctamente.
    Primer error: solo me aparece el nombre, no el apellido.
    Corrijo los settings y hago clic en "Actualizar datos". Me
      aparece un pop up con el mensaje "DANICA. Unknown". Cierro el
      mensaje y me lleva a la home de Dánica.
    Intento nuevamente haciendo clic en "Desactivar el
      asistente". Nuevamente me aparece un pop up con el mensaje
      "DANICA. Unknown". Cierro el mensaje y me lleva a la home de
      Dánica.
  ¿Qué puede estar ocurriendo?
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by LeandroBraier** [comment]
Claro, pero entonces el problema es que hay una inconsistencia entras las
App y el formulario en la web.

el usuario es Lecu y el mail es

blackmagicargentina@gmail.com

2014-06-04 10:09 GMT-03:00 mkreyness notifications@github.com:

> Es un usuario que creaste desde el App ?
> Dame cual es el usuario y pruebo. Ya sabemos que el App tiene un
> solo campo que se llama "name", esto le pasaron mal la definicion de
> las pantallas a los hindues y quedó siempre asi, cuando te registras
> con facebook solo toman el dato "nombre" y nunca el Apellido.El 04/06/2014
> 9:42, LeandroBraier
> escribió:
> 
> Marce, estoy teniendo problemas con el Asistente Dánica en
> versión Web. Te cuento el proceso:
> En el mailing del Asistente, hago clic en el botón de abajo
> de todo "Haga clic aquí"
> Llego a mi página con mis settings del Asistente
> correctamente.
> Primer error: solo me aparece el nombre, no el apellido.
> Corrijo los settings y hago clic en "Actualizar datos". Me
> aparece un pop up con el mensaje "DANICA. Unknown". Cierro el
> mensaje y me lleva a la home de Dánica.
> Intento nuevamente haciendo clic en "Desactivar el
> asistente". Nuevamente me aparece un pop up con el mensaje
> "DANICA. Unknown". Cierro el mensaje y me lleva a la home de
> Dánica.
> ¿Qué puede estar ocurriendo?
> —
> Reply to this email directly or view
> it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/LeandroBraier/DanicaWeb/issues/30#issuecomment-45087903
> .

## 

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
Me reenvias el mail que te llegó desde el cual estas usando el link para 
entrar web ?

**Comment by LeandroBraier** [comment]
Enviado!

2014-06-04 14:15 GMT-03:00 mkreyness notifications@github.com:

> Me reenvias el mail que te llegó desde el cual estas usando el link para
> entrar web ?
> 
> On 04/06/2014 10:43 a.m., LeandroBraier wrote:
> 
> > Claro, pero entonces el problema es que hay una inconsistencia entras las
> > App y el formulario en la web.
> > 
> > el usuario es Lecu y el mail es
> > 
> > blackmagicargentina@gmail.com
> > 
> > 2014-06-04 10:09 GMT-03:00 mkreyness notifications@github.com:
> > 
> > > Es un usuario que creaste desde el App ?
> > > Dame cual es el usuario y pruebo. Ya sabemos que el App tiene un
> > > solo campo que se llama "name", esto le pasaron mal la definicion de
> > > las pantallas a los hindues y quedó siempre asi, cuando te registras
> > > con facebook solo toman el dato "nombre" y nunca el Apellido.El
> > > 04/06/2014
> > > 9:42, LeandroBraier
> > > escribió:
> > > 
> > > Marce, estoy teniendo problemas con el Asistente Dánica en
> > > versión Web. Te cuento el proceso:
> > > En el mailing del Asistente, hago clic en el botón de abajo
> > > de todo "Haga clic aquí"
> > > Llego a mi página con mis settings del Asistente
> > > correctamente.
> > > Primer error: solo me aparece el nombre, no el apellido.
> > > Corrijo los settings y hago clic en "Actualizar datos". Me
> > > aparece un pop up con el mensaje "DANICA. Unknown". Cierro el
> > > mensaje y me lleva a la home de Dánica.
> > > Intento nuevamente haciendo clic en "Desactivar el
> > > asistente". Nuevamente me aparece un pop up con el mensaje
> > > "DANICA. Unknown". Cierro el mensaje y me lleva a la home de
> > > Dánica.
> > > ¿Qué puede estar ocurriendo?
> > > —
> > > Reply to this email directly or view
> > > it on GitHub.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > 
> > > <
> > > https://github.com/LeandroBraier/DanicaWeb/issues/30#issuecomment-45087903
> > > 
> > > .
> > 
> > ## 
> > 
> > Leandro Braier
> > Producción Audiovisual & Social Media
> > Benteveo Producciones http://benteveo.tv
> > Móvil 1158717399
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/LeandroBraier/DanicaWeb/issues/30#issuecomment-45091630
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/LeandroBraier/DanicaWeb/issues/30#issuecomment-45121483
> .

## 

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399
