### ISSUE TITLE
Productos Asistente Dánica

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/DanicaWeb#32]
Marce, no recuerdo si antes lo habíamos hablado, creo que sí, pero necesitamos que en el listado de productos que puedan aparecer en el Asistente Dánica estén solo los distintos tipos de Margarina, no las tapas de empanadas o tartas. MS vio un caso de estos hoy en su mailing. ¿Por favor lo asegurarías?

abrazo

**Comment by mkreyness** [comment]
Hecho no esta, asi que no creo haberme enterado de este pedido.
Ahora lo modifico.

**Comment by LeandroBraier** [comment]
Pudiste aplicarlo MK? Así cierro el ticket.
A mí no me llegaron más las tapas.

**Comment by mkreyness** [comment]
```
Si, ya esta funcionando asi desde hace unos dias.El 16/07/2014 9:17, LeandroBraier
  escribió:

  Pudiste aplicarlo MK? Así cierro el ticket.
    A mí no me llegaron más las tapas.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by LeandroBraier** [comment]
Perfecto, gracias!
