### ISSUE TITLE
Segunda Receta Asistente Dánica

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/DanicaWeb#33]
Necesito cambiar la segunda receta del Asistente Dánica en los mailings diarios. 

Necesito que la segunda receta no sea la del día siguiente, sino una sugerencia alternativa para ese mismo día. Desde el punto de vista del proceso, creo que lo que te cambia es que tenés que seleccionar 2 por día en los mailings diarios.

Me confirmás cuando está esto Marce?

Gracias!

**Comment by mkreyness** [comment]
O sea, lo que decis es que al dia siguiente no le vuelva a aparecer como 
primera la misma que le mostro el dia anterior como segunda ?

**Comment by LeandroBraier** [comment]
Exacto, MK. Habría que cambiar el texto que incluimos sobre la segunda receta, obviamente, pero es lo vemos con Fede una vez que lo impactes.

**Comment by mkreyness** [comment]
```
listo, ya la 2da receta (en los que se manda al menos dos dias
seguidos) no se vuelve a repetir al dia siguiente.El 16/07/2014 9:18, LeandroBraier
  escribió:

  Exacto, MK. Habría que cambiar el texto que incluimos sobre la
    segunda receta, obviamente, pero es lo vemos con Fede una vez
    que lo impactes.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by LeandroBraier** [comment]
Gracias MK!

Fede, necesitamos cambiar el texto de presentación de las segundas recetas en el mailing diario del Asistente. El texto nuevo debería decir:

"¿No es justo lo que tenías ganas de cocinar hoy? Aquí te facilitamos una segunda sugerencia:"

Avisame cuando esté.

abrazo

**Comment by FAAREIA** [comment]
Ok no hay problema, para no buscar mucho, en que template debería de agregar eso? Ahora en 5 me voy a fijar igual

**Comment by LeandroBraier** [comment]
Es solo el Mailing Diario, para el que selecciona todos los días en el
Asistente.

**Comment by FAAREIA** [comment]
Ahi esta hecho, igualmente esperemos a que nos confirme Marce K si esta OK. El cambio fue hecho en el archivo "mailing-diario-1T.html"
Si es otro archivo Marce, decime.

**Comment by mkreyness** [comment]
Eso se usaba antes de que agregaramos los productos en el mailing.
Los templates que se usan actualmente son los que se llaman 
mail1productosT, mail2productosT, etc.
O sea que se cuenta no por las recetas sino por los productos.
Aca tenemos un problema porque tanto en el que tiene tildado todos los 
dias como el que tiene tildado dia por medio, se usa el template 
mail5productosT.html, y ahora deberian ser 2 distintos, ya que en un 
caso realmente son recetas para 2 dias, y en el otro son 2 alternativas 
para el mismo dia.
Ya modifique el programa recien para que en este caso que use 
mail51productosT.html en vez de mail5productosT.html

O sea, en definitiva, modificalo solamente en el archivo 
"mail51productosT.html"

**Comment by LeandroBraier** [comment]
Gracias MK!

Me avisás Fede cuando está hecho?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-07-16 15:39 GMT-03:00 mkreyness notifications@github.com:

**Comment by FAAREIA** [comment]
http://danica.com.ar/html/mail51productosT.html
Ahi se puede ver online.

**Comment by LeandroBraier** [comment]
Fede, no veo el texto cambiado. Veo el texto anterior, puede ser?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Fijate ahora Lea, estaba mal el nombre de la imagen. Dale F5, que
seguramente tenes cacheado el html

2014-07-16 16:07 GMT-03:00 LeandroBraier notifications@github.com:

**Comment by LeandroBraier** [comment]
Ahí lo vi. Está mal ubicada la frase. Esa no es la que tenías que
reemplazar. La que tenés que reemplazar es:

Para el resto de la semana también tenemos sugerencias para facilitarte:

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-07-16 16:14 GMT-03:00 Federico Arena notifications@github.com:

**Comment by mkreyness** [comment]
Es que no es una imagen lo que hay que cambiar, es este texto:

Para el resto de la semana también tenemos sugerencias para facilitarte:

**Comment by FAAREIA** [comment]
ahhhhhhhhhhhh
ahora si

**Comment by FAAREIA** [comment]
Ya esta listo, f5 por si las dudas

**Comment by mkreyness** [comment]
se ve bien pero el visor online de los mails todavia no lo esta usando, 
ahora reviso.

**Comment by LeandroBraier** [comment]
Ahora sí lo veo perfecto!

Gracias!

**Comment by mkreyness** [comment]
Listo ya lo arregle.
