### ISSUE TITLE
Favicon de Danica. 

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/DanicaWeb#34]
Fede, necesito que armes el Favicon de Dánica. 

Decime para qué fecha puede estar subido.

abrazo

**Comment by FAAREIA** [comment]
Fijate ahi lea:
http://www.benteveo.tv/_danica/
Teniendo en cuenta que el logo completo es imposible de que entre, y de que la palabra también ya que tiene bordes, decidí ponerle la cara de la chica. Decime si te parece bien.
Lo muy malo del favicon es que con un F5 no se actualiza muchas veces, por lo que las pruebas siempre van a estar en una url distinta. Tenganlo en cuenta para el cliente.

**Comment by LeandroBraier** [comment]
Gracias Fede!

La cara de la chica no debería ir porque no quieren que tenga un lugar tan preponderante. Tenemos que pensar en otra cosa.  

Sé que es algo chico pero te lo pido tanto como maquetador como diseñador. Busquemosle una vuelta creativa. Sé que es difícil, yo lo intenté pero no pude.

Por los URL nuevos no hay problema.

abrazo

**Comment by FAAREIA** [comment]
Fijate en estas opciones y tené en cuenta que:
- Mostrar el logo completo implica que no se vea nada, va a quedar todo comprimido y sin entenderse.
- La chica no hay que mostrarla, ya que no puede quedar en un segundo plano teniendo en cuenta que no hay espacio ni niveles de lectura en algo tan chico.
- De la palabra de la marca, la unica letra a usar es la "D", excepto que la marca haya usado en alguna pieza otra letra como algo minimamente representativo.
- La soga puede ser otro elemento, pero lo probé y no se entiende mucho.

http://www.benteveo.tv/_favicons/danica1.html
http://www.benteveo.tv/_favicons/danica2.html
http://www.benteveo.tv/_favicons/danica3.html

Si es por mi, me quedo con el 1.

**Comment by LeandroBraier** [comment]
Me gusta la 1 también.

La 2 fijate si puede quedar más prolijo el bordecito rojo, sobre todo abajo
a la derecha se nota desprolijo. Esa opción también puede andar.

Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-07-29 12:58 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Fijate ahi lea, la mejoré bastante.
http://www.benteveo.tv/_favicons/danica4.html

**Comment by LeandroBraier** [comment]
Me gusta, pero sigo viendo puntitos blancos alrededor del borde rojo. Si me
pasás el psd te lo resuelvo en un toque.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
http://www.benteveo.tv/_favicons/danica5.html
fijate ahi lea, estuve leyendo un toque y creo que no hay problemas con png 24bits

**Comment by LeandroBraier** [comment]
Está bueno. Sigue siendo más prolija la versión 1 me parece, colocá esa
directamente en el sitio actual de Dánica.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Ahi esta listo Lea, me parece es la que mas contrasta y tiene más presencia ;)

**Comment by LeandroBraier** [comment]
Gracias Fede! Quedó bárbaro. Esperemos después a ver qué dice el cliente cualquier cosa pero me gusta como quedaron los dos Favicons por ahora.
