### ISSUE TITLE
Agregar Nuevos Boards de Pinterest al Embed

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/DanicaWeb#35]
Fede, ya tenemos 6 boards en el Pinterest de Danica. La página de Comunidad en esa parte se ve muy vacía. Cuando puedas sumale todas las boards así se ve más colorido y completo el marco.

http://es.pinterest.com/danicaargentina/

**Comment by FAAREIA** [comment]
http://www.danica.com.ar/danica/comunidad.html
