### ISSUE TITLE
El buscador de profesionales vacío lleva al buscador de productos del Hogar

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/DanicaWeb#36]
1. Entro a Productos/Profesionales.
2. Entro a la sección Panadería.
3. Uso el buscador para buscar "Cremalda".
4. No encuentra nada ni aparece el jpg que dice que "No hay resultados." (BUG 1)
5. Uso el buscador para buscar "Crema"
6. Sí me aparece el jpg de "No hay resultados" pero las secciones que veo debajo del buscador son las de "hogar": Margarina y Tapas.

**Comment by mkreyness** [comment]
Ahora lo reviso y arreglo.

**Comment by mkreyness** [comment]
por lo que acabo de ver el problema es que el template no tiene la parte 
esa de que diga busqueda sin resultados, miren:
HOGAR SIN RESULTADOS:
http://www.danica.com.ar/html/sinresultadosproductoshogarT.html

PROFESIONALES SIN RESULTADOS:
http://www.danica.com.ar/html/sinresultadosproductosprofesionalesT.html

ya le ajuste el link del buscador que tenia mal (o sea, ahora busca bien 
si pones crema despues de que no encontraste cremalda), pero hay que 
corregir el contenido, porque se ve que quedo copiado de la pagina CON 
resultados.
Lo podras ver vos Fede eso ? No quiero romper el HTML.

**Comment by LeandroBraier** [comment]
Gracias Marce! Se lo paso a Fede entonces.

**Comment by FAAREIA** [comment]
http://www.danica.com.ar/html/sinresultadosproductoshogarT.html
http://www.danica.com.ar/html/sinresultadosproductosprofesionalesT.html
