### ISSUE TITLE
Cambiar la Playlist de YouTube en Comunidad Danica 

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/DanicaWeb#37]
Fede, sin apuro, cambiemos la Playlist embebida de YouTube en la págin Comunidad de la web de Dánica por esta:

https://www.youtube.com/watch?v=V-5JRgNTsoU&list=PL4wC5kB4VtzHI8oBOsdRHZx9Z9a5Xxq8J

**Comment by FAAREIA** [comment]
Hecho
http://www.danica.com.ar/danica/comunidad.html

**Comment by LeandroBraier** [comment]
Gracias!
