### ISSUE TITLE
Iconos Categorías

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/DanicaWeb#4]
El fondo me aparece igual en Mac OS. Para no alterar nada en los otros navegadores, borrá el ícono de comida que hay en el fondo de las páginas de categorías en esa misma área para que no se note el corte y listo.

**Comment by FAAREIA** [comment]
Hola Lea, en realidad el bug lo tiene safari en ese objeto porque todo esta con ese mismo PNG, de ahi salen casi todas las imágenes del sitio. Busqué y algunos dicen cosas pero nada certero, tendría que probarlo en vivo. Voy a tratar de conseguir una mac y probar.

**Comment by LeandroBraier** [comment]
Como quieras, para mi con ese mismo cambio que te digo ya te quedás tranquilo y perdés menos tiempo. De hecho, por ahora soy el único que se dio cuenta de eso, asi que no hay prioridad.

**Comment by FAAREIA** [comment]
Es que esta armado diferente, el fondo es un pattern y el bug se da porque, interpreta algo mal y lo transparente te lo pone blanco.

**Comment by LeandroBraier** [comment]
Entonces te propongo subirlos en .GIF, que también aceptan transparencia. Cómo lo ves?

**Comment by FAAREIA** [comment]
Me gusta la idea de generar un archivo aparte a ver como lo toma, igualmente me gustaría probarlo en una mac ya que creo que se resolvería rápido. Vos tenes teamviewer?

**Comment by LeandroBraier** [comment]
No, pero ya lo estoy bajando. Lo decís para ver la página cómo la veo yo?

**Comment by FAAREIA** [comment]
Claro, me meto un toque a tu pc, si no hay drama, y desde el chrome o safari pruebo algunas propiedades.
Avisa!

**Comment by LeandroBraier** [comment]
me estoy yendo de la compu, a la vuelta lo hacemos abrazo

**Comment by LeandroBraier** [comment]
volví Fede! Cuando quieras salimos

**Comment by FAAREIA** [comment]
dale, skype asi organizamos

**Comment by LeandroBraier** [comment]
dame un min que reinicio, ya que está bastante lenta.

On Thu, Feb 20, 2014 at 7:09 PM, Federico Arena notifications@github.comwrote:

> dale, skype asi organizamos
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/LeandroBraier/DanicaWeb/issues/4#issuecomment-35675353
> .

## 

Leandro Braier
Producción Audiovisual & Social Media
Móvil 1158717399

**Comment by LeandroBraier** [comment]
ya reinicié, estoy en skype cuando quieras
