### ISSUE TITLE
Falla en Acortar Danica.Tw

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/DanicaWeb#42]
Marce, estamos teniendo el mismo problema que teníamos con las url de Dánica y Paty en el acortador Danica.tw. Ejemplo:

http://danica.tw/aderezodelmediterraneo

Si entendí bien hay que autorizar a correr los .cgi desde el .htaccess de este dominio también.

Me avisás cuando esté hecho?

abrazo

**Comment by LeandroBraier** [comment]
Marce, arreglaron esto al final? En este momento los acortadores volvieron a funcionar mal. Por favor necesito resolverlo URGENTE.

abrazo

**Comment by mkreyness** [comment]
No entiendo, si lo usas en vez de poniendo danica.com.ar te andan bien y 
con danica.tw te andan mal ?

**Comment by LeandroBraier** [comment]
Los de danica.tw no funcionan. Los de danica.com.ar si funcionan. Pero esto mismo nos paso antes con los dominios generales "paty.com.ar" y "danica.com.ar". Al ir al dominio se descarga un archivo solo que dice "descarga" sin formato. Por eso te lo aclaré y te recordé cómo solucionaron eso en ese momento.

Chequeá por vos mismo todos los links de "danica.tw" en el twitter de Danica:

https://twitter.com/DanicaArgentina

**Comment by mkreyness** [comment]
Ahi entendi, sacaron el permiso para correr .pl desde la web.
Entonces tampoco debe estar andando el SEARCH, ojo.
Cambie todo esto para que funcione con .cgi en vez de .pl, y rehice 
todos los links, pero habria que mandarles una linda puteada a los de 
Duplika por estar cambiandonos las cosas sin avisar.

**Comment by mkreyness** [comment]
Yo probe y con danica.com.ar tampoco funcionaban, no depende del dominio.
Fijate ahora deberian andarte todos, pero seguro se jodio el search tambien.

**Comment by LeandroBraier** [comment]
Ahora me funciona bien MK. Gracias!

A qué te referís por el search?

En el sitio el search funciona bien.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-02-26 20:05 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
```
El buscador, que tambien es un programa .pl como eran estos index.pl
que dejaron de funcionar.
Pero parece que lo que hicieron de permisos afectó solo a las
carpetas que no fueran cgi-bin, lo que esta en cgi-bin (el buscador)
anda bien.

Che la moraleja de todo esto es que GitHub no sirve para
emergencias. El mail del 13 de enero en el que me asignaste esto,
jamas lo vi, porque estaba entre otros 30 de temas en GitHub que no
eran para mi.

Cuando hay una cosa seria asi:
1) mandame un mail directo, explicando el problema o referenciando a
lo que mandaste por GitHub, pero plis LLAMA MI ATENCION.
2) Yo recibo unos 500 mails diarios (no todos requieren mi
respuesta, muchos son robots que me informan cosas) y contesto facil
200/300, asi que no puedo darme el lujo de dejar cosas para otro
dia, ni siquiera en fin de semana, ya que lo que no vi en el dia no
lo voy a volver a ver nunca mas.
Si no te conteste, es SEGURO que no lo vi, remandame si queres por
SMS o cualquier otra via que se te ocurra.


El 26/02/2015 a las 20:09, LeandroBraier escribió:
Ahora me funciona bien MK. Gracias!

  A qué te referís por el search?

  En el sitio el search funciona bien.

  Leandro Braier
  Producción Audiovisual & Social Media
  Benteveo Producciones <http://benteveo.tv>
  Móvil 1158717399

  2015-02-26 20:05 GMT-03:00 mkreyness
  <notifications@github.com>:

  > Yo probe y con danica.com.ar tampoco funcionaban, no depende
  del dominio.
  > Fijate ahora deberian andarte todos, pero seguro se jodio el
  search
  > tambien.
  >
  > On 26/02/2015 08:02 p.m., LeandroBraier wrote:
  > >
  > > Los de danica.tw no funcionan. Los de danica.com.ar si
  funcionan. Pero
  > > esto mismo nos paso antes con los dominios generales
  "paty.com.ar" y
  > > "danica.com.ar". Al ir al dominio se descarga un archivo
  solo que dice
  > > "descarga" sin formato. Por eso te lo aclaré y te
  recordé cómo
  > > solucionaron eso en ese momento.
  > >
  > > Chequeá por vos mismo todos los links de "danica.tw" en
  el twitter de
  > > Danica:
  > >
  > > https://twitter.com/DanicaArgentina
  > >
  > > —
  > > Reply to this email directly or view it on GitHub
  > > <
  >
```

https://github.com/LeandroBraier/DanicaWeb/issues/42#issuecomment-76294419
      > >.
      >
      > >
      >
      > —
      > Reply to this email directly or view it on GitHub
      >
https://github.com/LeandroBraier/DanicaWeb/issues/42#issuecomment-76294883
      > .
      >
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by LeandroBraier** [comment]
Dale, MK. Quedamos así para los próximos casos. Creo que a mí se me pasó
insistirte también entre todo el maremagnum de laburo que estamos teniendo,
sino ya te hubiera insistido también.

Gracias una vez más MK!

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-02-26 21:00 GMT-03:00 mkreyness notifications@github.com:
