### ISSUE TITLE
Estimación de tiempos de desarrollo "Dar la nota"

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/DanicaWeb#43]
Marce, hicimos una propuesta para DÁNICA y, en función de los tiempos de desarrollos, vemos si la aplicamos o no.

Lo que necesitamos es una página web que permita jugar al siguiente juego:

http://www.karaokeparty.com/en/
https://www.youtube.com/watch?v=BVy5mX3gaDM

Es el mismo que usa Guido Kaszka en el programa "Dar la nota". En nuestro caso, la funcionalidad sería más sencilla aún. El micrófono detecta si hay voz o no hay voz nada más. Otorga puntajes según si había voces en los tramos de tiempo correctos.

Si no soy claro avisame y te mando la presentación.

abrazo

**Comment by mkreyness** [comment]
Humm, esta claro, pero el ejemplo que me pasás esta hecho con Flash, yo 
de flash ni idea.
Estoy investigando si es manejable con el getUserMedia API que traen los 
browsers, te contesto en un rato.

**Comment by LeandroBraier** [comment]
Genial Marce. Averigualo por esa via.

En caso de ser Flash, tenemos a alguien que anima y saber algo de AS esa
parte. A él necesitaría darle algo que le permita al sistema detectar a
través del mic si hay voz o no hay voz. Eso sabés como hacerlo?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-03-27 17:32 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Si se usa Flash la deteccion (pidiendo permiso al usuario primero) la 
hace directamente Flash, pero no tengo idea como.
Igual ya tengo claro como se hace, pero:
1) no funciona en browsers viejos
2) no funciona mobile (tampoco lo haria el Flash en un iphone, anyways).

Entiendo que ademas alguien deberia proveer la "pista" que indica cuando 
es aceptable que haya sonido y cuando no, eso lo armarian a mano ?
Porque obviamente no puedo hacerlo automatico a partir de un mp3 ya que 
volumen de musica hay todo el tiempo.
Habria que:
- mostrar la pista hecha de tramos (supongo que con la letra), por 
  renglones y escrolando hacia arriba como en "Dar la Nota"
- superponer sobre esa pista cuando se detecta volumen de microfono 
  (habria que definir un nivel minimo, eso si es jodido porque no tenemos 
  control fisico sobre la sensibilidad del microfono, capaz habria que 
  poner una primer pantalla de test para que ajuste la sensibilidad).
- medir las coincidencias (no se con que grado de precision) e ir 
  acumulando puntos.

Todo eso es factible, tiene mucho de grafica y hay que ver como hacer 
que escrole en forma suave y aceptable.

Tambien la persona tendria que registrarse con FB/TW etc para llevar un 
score ?
Si queres mandame la presentacion completa asi tengo una idea mas 
general de todo lo que tendria que tener el sitio.

**Comment by LeandroBraier** [comment]
MK, te respondo en detalle en un rato, pero antes necesitaría saber el tema
de tiempos.

1) Cantidad de horas que te llevaría la versión tuya (la versión flash la
descartamos)

2) Si podríamos tenerla lista para el 1 de mayo.

Confirmame estas dos cosas y te respondo los demás detalles.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-03-27 18:01 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Si no se en que mas consiste, dificil poder estimar tiempos.
Yo te puedo estimar tiempos de armar la parte interna tecnica, pero me 
imagino que va a llevar mucha grafica y bastante dinamica.
Ponele que lo mio llevaria unas 50 horas, incluyendo ajustes, de todos 
modos "tenerlo listo" no depende para nada de mi.

**Comment by LeandroBraier** [comment]
Gracias Marce! Esa info me sirve para calcular.

El diseño no creo que lleve tanto tiempo, porque tenemos un keyvisual y el fondo del juego va a ser el spot de Dánica que estamos filmando en breve. Lo consulto con Fede. Fede, ¿cuántas horas calculás que te llevaría hacer el diseño de este juego si yo te paso el keyvisual estético?

También paso el Slide de la presentación donde explicamos el juego y además la captura en particular del juego conducido por Guido Kaszka. La estética del juego sería esa: el video y los ladrillitos con un cursor pasando sobre ellos, al modo de la famosa pelotita que va sobre la letra de una canción en un Karaoke.

La canción sería una sola y siempre la misma: la canción del Spot de Dánica. La idea es machacar el jingle lo más posible (juajua). 

![dar-la-nota](https://cloud.githubusercontent.com/assets/6719872/6879314/ca815bea-d4d0-11e4-9bb1-20a5337e9ae8.jpg)
![slide-2](https://cloud.githubusercontent.com/assets/6719872/6879319/d6716026-d4d0-11e4-9a26-4ddf74d3f5a2.png)

**Comment by FAAREIA** [comment]
Si ya lo tienen todo definido, no tendría que diseñar nada, solo maquetar y readaptar fondos.
Las notas que van a formar parte del video, hasta capas que son parte del mismo video.
Necesitaría saber un poco más que va a tener cada pantalla para pasar tiempos. Por ejemplo, en la pantalla del video capas que solo inserto el flash y listo.

**Comment by LeandroBraier** [comment]
Gracias Fede!

Si repasás la conversación para arriba que tuvimos con Marce vas a ver que en realidad Flash quedó descartado. Lo vamos a hacer con el sistema que dice Marce: getUserMedia API.

Las pantallas serían dos:

1) La del juego con el video de fondo. Antes aparecería un pop up con un video que explica el juego y luego un botón que habilitaría empezar a jugar. Es decir, aquí entiendo que tu diseño tendría que ver con el juego en sí mismo en una única pantalla.

2) Una vez finalizado el juego, tendría que aparecer un ranking donde el usuario quedaría ubicado de acuerdo a su puntaje. En principio no hay premios, es simplemente un ranking de puntos como el que teníamos en el Homenaje de Dánica. La idea es que el usuario pueda compartir en Facebook cuánto puntaje obtuvo y su posición en el ranking con un botón directo.

Decime cuántas horas te llevaría aprox y si lo ves posible llegar a hacer para principios de Mayo teniendo en cuenta todas las entregas de Klaukol también. Yo lo veo posible siendo que está Braulio para redoblar fuerzas.

abrazo

**Comment by FAAREIA** [comment]
Por eso mismo digo, según entendí lo que dijo Marce es que era con Flash porque getUserMedia API es nuevo y no funciona en browser viejos ni en mobile, cosa que flash tampoco va en iphone.

Para Mayo llegamos, no lo veo complejo. Creo que con 40hs va a sobrar un poco, vamos a ver. Siempre es mejor calcularlo con el diseño ya terminado en realidad.

**Comment by mkreyness** [comment]
```
No, lo que yo digo es que algo hay que sacrificar.

Si se hace con getUserMedia se le dice al que se conecta que su
browser es viejo si no lo soporta.
Para que funcione mobile si habria que contratar a alguien que haga
la version flash, e igual no andaria en iPhones.

No hay una solucion que sirva para todo.

El 30/03/2015 a las 10:14, Federico
  Arena escribió:


  Por eso mismo digo, según entendí lo que dijo Marce es que era
    con Flash porque getUserMedia API es nuevo y no funciona en
    browser viejos ni en mobile, cosa que flash tampoco va en
    iphone.
  Para Mayo llegamos, no lo veo complejo. Creo que con 40hs va a
    sobrar un poco, vamos a ver. Siempre es mejor calcularlo con el
    diseño ya terminado en realidad.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by LeandroBraier** [comment]
Claro, yo había entendido esto mismo que dice Marce, lo consulté con Eze y
me dijo que DESCARTAMOS la versión Flash. Lo hacemos para Browsers Nuevos y
Tablets con el getuserAPI.

Gracias por el monto de horas, ahora lo paso entonces y les confirmo si
arrancamos con esto o no. Si queda aprobado, tendríamos que arrancar a
armar el sistema antes de tener listo el spot porque el spot va a estar
final recién en la tercera semana de abril. O sea que recién ahí vamos a
poder saber en qué segundo de la música hay voz y en qué segundo no. Quizá
10 días antes podríamos tener la canción grabada, eso sí. No necesitamos el
video, pero igual en las primeras dos semanas de abril tendríamos que armar
el sistema con otra canción de la misma duración "20 segundos" para testear
el sistema.

Si se confirma entonces les aviso.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-03-30 10:17 GMT-03:00 mkreyness notifications@github.com:
