### ISSUE TITLE
Consulta por subida de Nueva Receta a Dánica

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/DanicaWeb#45]
Buen día Marce, yo tengo entendido que ya quitaste el CMS del Sitio de Dánica.

Sobre esta base, tenemos posibilidad de subir una nueva receta? En caso de poderse, qué necesitás que te mande? un excel?

abrazo

**Comment by LeandroBraier** [comment]
Marce, porfa apenas puedas confirmame si podemos hacer esto.

abrazo

**Comment by marcsuse** [comment]
LEan,

Que receta hay que cargar ?

se parece a alguna de las existentes ?

asi se puede duplicar el registro y editar solo las diferencias

MARCELO SUSEVICH
BENTEVEO
Guatemala 5582 - Piso 2 (CABA) Argentina
T. +54 11.52.54.73.63
E. marcelo@benteveo.tv
W. www.benteveo.tv

**Comment by LeandroBraier** [comment]
Si, se parece a esta receta, solo que va sin video en principio.

http://webcache.googleusercontent.com/search?q=cache:eER-PXEF2lAJ:danica.tw/danica/cookies-dos-chocolates.html+&cd=3&hl=en&ct=clnk&gl=ar

http://webcache.googleusercontent.com/search?q=cache:eER-PXEF2lAJ:danica.tw/danica/cookies-dos-chocolates.html+&cd=3&hl=en&ct=clnk&gl=ar

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-04-13 10:43 GMT-03:00 marcsuse notifications@github.com:

**Comment by mkreyness** [comment]
Tengo otra propuesta:
Que tal si monto el CMS de Danica en el sitio de Benteveo, apuntando 
obviamente a la base de datos de Danica ?

Lo mejor de ambos mundos: se le puede seguir dando el servicio sin darle 
la herramienta.

**Comment by LeandroBraier** [comment]
jajaj Excelente!

Hagamos eso entonces y yo subo la receta.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-04-13 15:56 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Bueno funciona pero ojo, hasta ahi nomas, porque fisicamente las fotos y 
videos obviamente no estarian subiendo al server correcto (ni te muestra 
las fotos.
Podes editar los textos y se van a crear las paginas, pero las 
fotos/videos hay que subirlas manualmente al servidor real de ellos de 
otra manera.

Fijate lo que puedas completar asi (si queres subí las fotos, y yo 
despues las traslado de servidor).

**Comment by LeandroBraier** [comment]
Dale, genial. El link del cms es el de siempre entonces?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-04-13 16:13 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Pero con www.benteveo.com.ar en vez de www.danica.com.ar
Dicho sea de paso, www.danica.com.ar no anda, trasladaron el dominio a 
otro lado ??
En tal caso es medio al cuete agregarle recetas.

**Comment by mkreyness** [comment]
Ah, cierto que se les vencio. Y que piensan hacer con eso ??? Todavia no 
lo renovaron.

**Comment by LeandroBraier** [comment]
jajaj no?

Teóricamente sí. Figura como que no? Me pasás captura de eso?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-04-13 16:22 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Si, ahora figura renovado en el NIC (hace un rato no).
Tal vez todavia no se propagó, funcionar no funciona, hay que esperar un 
rato.

**Comment by LeandroBraier** [comment]
Marce, me pasarías el link final del cms al que puedo acceder? Porque el que me aparece es el que usábamos para las marcas:

http://www.benteveo.tv/cgi-bin/cms.pl

**Comment by mkreyness** [comment]
```
Es "recetas.pl", no "cms.pl":

http://www.benteveo.tv/cgi-bin/recetas.pl


El 16/04/2015 a las 21:23,
  LeandroBraier escribió:


  Marce, me pasarías el link final del cms al que puedo acceder?
    Porque el que me aparece es el que usábamos para las marcas:
  http://www.benteveo.tv/cgi-bin/cms.pl
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by LeandroBraier** [comment]
cierto. Gracias MK!

abrazo

**Comment by LeandroBraier** [comment]
Marce, corregí el nombre de una receta y ahora me da error. Puede ser?

http://www.danica.com.ar/danica/galletas-con-chispas-de-chocolate.html

**Comment by LeandroBraier** [comment]
Ahora funciona pero no se sube la foto. Me habías dicho que te avisara que vos tenías que cambiarla manualmente de servidor.

abrazo

**Comment by mkreyness** [comment]
Claro, porque la esta subiendo al servidor de Benteveo.
Decime cual fue la receta que cargaste asi lo copio manualmente.

**Comment by LeandroBraier** [comment]
Es esta:

http://www.danica.com.ar/danica/galletas-con-chispas-de-chocolate.html

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-04-17 13:39 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
si, despues la vi. Ya la pasé, fijate.

**Comment by LeandroBraier** [comment]
Gracias MK! Ya lo vi impactado online.
