### ISSUE TITLE
Estimación de tiempos y horas para Restyling Web Dánica

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/DanicaWeb#46]
Fede, me llegó el pedido de modificaciones para Dánica. Como suponíamos, es un poquito más de lo que se anticipó. Te paso el detalle. 

Lo que necesito es que me pases 
1. para cuando podríamos tener lista la Etapa 1 y para cuando la Etapa 2. 
2. cuántas horas de tu equipo (y en caso de ser necesario también cuántas horas de MK) se requerirían para hacerlo. Esto es crucial para hacer el presupuesto y que nos lo apruebe el cliente.

ETAPA 1 LOOK&FEEL: 
Colores: Acomodarlos para que queden acordes al Key Visual de la nueva campaña.
Tipografía: Idem Key Visual campaña.
Imágenes del Slideshow: No tendría más la nube, todo el espacio disponible lo ocuparía la foto del slideshow. Referencia: http://exquisita.com.ar/

Las fotos las cambiaríamos por otras con un estilo diferente, más naturalista, caseras, nada que se vea artificial. Tendría recetas hechas con Dánica (Tipo Banners). Cada imagen contendría Receta + Pack Danica + Claim Campaña.

ETAPA 2: RESTYLING A FONDO

FORMATO GENERAL:
1. Pasar el sitio a Responsive

HOME

Llevaría varias modificaciones. Entre el slideshow y la pasarela de recetas, habría 3 links con imágenes con texto dentro. Una llevaría a la sección "Sabías que la Margarina.." otro al Spot de Dánica y otro a la sección Comunidad. Referencia: http://www.citroen.com.ar/

Debajo de eso, en lugar de pasarela de recetas, habría pasarela de productos.

Referencia: http://exquisita.com.ar/productos/

COMUNIDAD

Tendría un formato más parecido a Pinterest. En lugar de embeds de una página de Facebook o de un perfil de Twitter, sería una especie de board que tendría un embed que mostraría solo la última publicación de Facebook, otro la última de Twitter y así.

Referencia: http://www.citroen.com.ar/citroen-y-vos/citroen-social.html

RECETAS

Agregar un ranking de las recetas con más visita.

Agregar filtros al buscador: de acuerdo a la sección, a si es dulce o salada, a qué productos incluye, etc.

¿SABIAS QUE LA MARGARINA ES…?

Agregar una sección que cuente los beneficios de la Margarina.

**Comment by LeandroBraier** [comment]
Fede, nos reunimos con el cliente y resultó más sencillo incluso de lo que pensabamos. Te paso las especificaciones de los cambios así me hacés un estimado de horas final para este trabajo.

Responsive: hablamos de las dos alternativas posibles: hacerlo responsive en serio o sólo sumar una web adaptada a mobile. Pidieron que coticemos ambas, pero probablemente procedamos con la más rápida.

Look&Feel: Cambiar el color del toldito por el color KeyVisual.

Header: En lugar del slideshow, iría un video como hicimos en la web de Francisco o en la Nueva de Klaukol 1.0. Es un video de planos bien detallados y food porn que realce los atributos. Probar mezclando planos del comercial y de recetas ya filmadas por nosotros.

En la versión mobile sería un slideshow con imágenes de la misma estética.

Debajo del header habría 3 cuadrados como los de esta web: http://www.citroen.com.ar/

Uno llevaría a la página de Beneficios, que explicaría los beneficios de la margarina. Los otros 2 cuadrados de abajo sugeridos por Maxi llevarían a las páginas de: Comunidad de Redes y Recetas

Beneficios: La estética sería un pizarrón con un slideshow transparente encima que simularía que los textos se escriben en tiza sobre el mismo y, cada 5 seg, se difuminan y aparece otro.

Comunidad: Sería un mural de posteos de diferentes redes como habíamos hablado. 

Agregado pequeño: Agregado del display de ingredientes que aparece en la receta en los resultados del buscador también.

Home: Poner Galería de Productos simil la de Recetas de hoy en la Home. Que sean 3: Dánica Clásica, Dorada y Soft Light 

Buscador: Que tenga sugerencias mientras se escribe simil Google

Referencias:

http://www.citroen.com.ar/

http://www.granjadelsol.com.ar/mitos.html#

Cuando tengas el presupuesto pasame porfa. Puede ser mañana.

abrazo

**Comment by LeandroBraier** [comment]
Fede: necesitaría también para ir pidiéndole a Marino, el realizador, las specs del video que iría en el header. Tamaño, resolución, peso, etc.

Cualquier cosa, si necesitamos comunicarse cuando yo no estoy la semana que viene escribile a: marinomor@gmail.com

abrazo

**Comment by FAAREIA** [comment]
Hola Lea, no hay specs para el video realmente. Lo único es que tiene que ser formato 16:9 en lo posible. Y también tengan en cuenta que si el video va de punta a punta del monitor, puede que quede medio alto y si el cliente no quiere que ocupe todo o casi todo el alto de pantalla probablemente haya que ocultarle un poco el alto para que no parezca un video fullscreen.

**Comment by LeandroBraier** [comment]
Gracias Fede! Con eso estamos. Cuando puedamos pasame el estimado de horas tuyo y si considerás que necesitamos pedirle a Marce también.

abrazo

**Comment by FAAREIA** [comment]
Yo creo que hacer la versión responsiva directamente va a ser más fácil, ya que sino habría que diseñar la versión mobile y también algo de programación va haber.

Con respecto a lo último que me pediste:
Hacerlo llevaría alredeor de 34hs.

Hacerlo responsive incluyendo al sitio entero también. 36hs+

Hacer una versión exclusiva para mobile podría llevar 60hs+ si tenemos en cuenta que hay que primero pensarla, después diseñarla y luego maquetarla y hacerla funcionar. Si bien podría ser solo un buscador de recetas lo cual reduciría los tiempos, aca el cliente puede aparecerse con cosas inesperadas si todo no se define bien de antemano.

**Comment by LeandroBraier** [comment]
Gracias Fede. Entonces la versión responsive serían 36 hs tuyas + 34 hs de los cambios específicos que te pedí?

Serían 70 horas en total, no?

Solo necesito confirmar si entendí bien.

**Comment by FAAREIA** [comment]
Si, asi es. Acuerdense que lo responsive aplica a lo nuevo + todo el resto del sitio

**Comment by LeandroBraier** [comment]
Exacto. Gracias Fede!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399
