### ISSUE TITLE
Restyling DanicaWeb

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/DanicaWeb#48]
Fede, te cargo este ticket principalmente para avanzar con tema Restyling, ya que no sé específicamente los detalles que te pasó Eze. 

Te paso el estado de temas de lo que tengo entendido que se está haciendo y decime en qué status estamos de cada cosa. Cualquier comentarios hacelo en este otro ticket: https://github.com/LeandroBraier/DanicaWeb/issues/47

Acá simplemente vayamos tachando o corrigiendo esta misma lista.

LISTADO DE TAREAS
1. Pasar el sitio a Responsive
2. Look&Feel: Cambiar el color del toldito por el color del KeyVisual.
3. Header: En lugar del slideshow, iría el video. Ya te lo pasaron a este video, verdad? En la versión mobile sería un slideshow con imágenes de la misma estética: Te paso una versión previa del video para que vayan probando: https://www.wetransfer.com/downloads/df54e1ceba137039a71b4debc527dfe120150527164731/813e68df9ace6aafd05c6dd626f2c5d320150527164732/548902
4. Debajo del header habría 3 cuadrados como los de esta web: http://www.citroen.com.ar/
5. Uno llevaría a la página de Beneficios, que explicaría los beneficios de la margarina. Los otros 2 cuadrados de abajo llevarían a las páginas de: Comunidad de Redes y Recetas
6. Beneficios: La estética sería un pizarrón con un slideshow transparente encima que simularía que los textos se escriben en tiza sobre el mismo y, cada 5 seg, se difuminan y aparece otro. Por ahora solo poner título y utilizar los siguientes textos en formato bullets: 

Es de orígen vegetal y sin colesterol 
Tus recetas salen más livianas
No tiene grasas trans
Es ideal para cocinar y no se quema al saltear
1. Comunidad: Sería un mural de posteos de diferentes redes como habíamos hablado.
2. Recetas: Van con algunos cambios.

a. Agregado del display de ingredientes que aparece en la receta en los resultados del buscador también.

b. Buscador: Que tenga sugerencias mientras se escribe simil Google

c. Nueva división y subdivisión de categorías de recetas. (entiendo que esto se lo pido a MK, no? Confirmame y se lo pido)

Las categorías van a pasar a ser dos: “Me encanta lo dulce” y “Amo lo salado”. Se desplegarían en dos columnas, con un top 5 de recetas más vistas de cada una en cada columna. Ya tengo toda la nueva clasificación y ranking de recetas para armar los top 5 de cada categoría en un excel que subí a DROPBOX  de BENTEVEO MAQUETADOR/DANICA

Dentro de cada una, se subdividirían en 4 niveles de dificultad: algo complicado (agregarla), moderado (actual "experto", cambiar el nombre), fácil (actual "medio", cambiar nombre) y muy fácil (actual "fácil", cambiar nombre). Esto está clasificado en el mismo excel.

Estos niveles de dificultad se mostrarían debajo del título de la receta en la página de dicha receta (y en los resultados del buscador también, de ser posible) mediante un código de cucharones de madera. 1 cucharón: Muy fácil. 2 cucharones: Fácil. 3 cucharones: Moderado. 4 cucharones: Algo Complicado.

Necesito que uds creen las categorías, adapten el diseño y agreguen la opción de filtrado de las mismas en el buscador de recetas. Yo me ocupo de volver a clasificar las recetas en el CMS.
1.  Home: Agregar Galería de Productos simil la de Recetas de hoy en la Home. Que sean 3: Dánica Clásica, Dorada y Soft Light
   http://www.danica.com.ar/danica/margarina-danica-clasica-1.html
   http://www.danica.com.ar/danica/margarina-danica-dorada.html
   http://www.danica.com.ar/danica/margarina-danica-untable-soft-light-1.html
2. Agregué nuevos productos a la página:
   http://www.danica.com.ar/danica/manterina.html
   http://www.danica.com.ar/danica/vegetalina.html

Referencias:
http://www.citroen.com.ar/
http://www.granjadelsol.com.ar/mitos.html#

Confirmame recepción en el ticket de comentarios que creé para tal fin: https://github.com/LeandroBraier/DanicaWeb/issues/47

**Comment by FAAREIA** [comment]
Perfecto

**Comment by FAAREIA** [comment]
Hola Lea, ahi te mando un par de cosas para mostrar, faltaría el bloque de recetas que cambió y hacer andar lo de beneficios.
Lo que si esta pero me parece raro que sea de esa forma, es que en resoluciones menores el video no aparece y aparece un slideshow. Lo que se podría hacer es cargar un video "pesado" para desktop y uno más liviano para mobile. Sería lo más congruente.
También falta lo responsivo y poner los cucharones a las recetas.

**Comment by LeandroBraier** [comment]
Gracias Fede!

Puede ser que no estén bien los links? Me parece que son rutas locales de
tu compu.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-05-28 14:43 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
ajaja, si lo son. Ahi van las posta:

http://benteveo.tv/_danica-beta/danica/home.html
http://benteveo.tv/_danica-beta/danica/comunidad.html
http://benteveo.tv/_danica-beta/danica/beneficios.html

**Comment by LeandroBraier** [comment]
Gracias Fede! Los veo bastante bien. Beneficios lo muestro así y lo del header también, es lo que hablamos con ellos y lo vimos en la web de airnbnb.

Habrá posibilidad de mostrar hoy también lo de recetas? Aunque sea hoy a última hora. Me interesa para mostrar que cambiamos las 2 categorías, incluimos los top 5 y el buscador corregido. Solo la página de inicio de recetas, no hace falta que los links funcionen perfecto.

Te paso algunos pequeños errorercitos de gráfica que veo en mi Retina Full HD en Chrome

HOME:
![captura de pantalla 2015-05-28 a la s 15 04 17](https://cloud.githubusercontent.com/assets/6719872/7867044/dd5d77f4-0549-11e5-860c-7d0fe12e4b48.png)
![captura de pantalla 2015-05-28 a la s 15 04 22](https://cloud.githubusercontent.com/assets/6719872/7867045/dd5ed5a4-0549-11e5-8615-0a908d6a4f1c.png)

BENEFICIOS:
![captura de pantalla 2015-05-28 a la s 15 04 58](https://cloud.githubusercontent.com/assets/6719872/7867046/dd5fd238-0549-11e5-90b9-fa41a0d6908c.png)

abrazo

**Comment by FAAREIA** [comment]
No llegamos Lea, tengo que hacer otras cosas. Mañana lo hacemos para el mediodía, lo que si el buscador no va a funcionar nunca porque no duplicamos todo dánica, sino pedazos para mostrar lo nuevo. Eso habría que mostrarlo directamente en el sitio online.

**Comment by FAAREIA** [comment]
Lo de la imagen, debe ser algo arrastrado del sitio viejo, lo otro lo vemos

**Comment by FAAREIA** [comment]
En las dos primera imágenes no veo el error lea

**Comment by LeandroBraier** [comment]
En la primera de la home, se ve que arriba el logo queda salido del toldito
y el menú está muy cerca del final del toldito. Habría que estirar un
poquito más el toldito para que entre entero. Abajo del header los tres
recuadros se pasan del toldito. Me parece que no queda bien eso. Tendrían
que quedar dentro del toldito.

Es eso nomás.

Y lo de recetas primera página podrá estar para mañana entonces?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-05-28 15:28 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Lo el logo siempre fue asi y lo del menú también. Fijate que esta igual que en la web actual pero con el toldo de otro color. Si parece que llega al borde el menú es porque el navegador no alcanza cierto ancho como dejarle el aire. Y en resoluciones menores, hasta 640px se adapta. Lo otro OK

**Comment by LeandroBraier** [comment]
Está bien, pero en la refe de Citroen no es así, así que modifiquemoslo
para que quede como en Citroen. Es parte del restyling cambiar eso.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-05-28 15:50 GMT-03:00 Federico Arena notifications@github.com:

**Comment by braulio-evangelisti** [comment]
Hola Lea 
Fijate ahi, actualizá la home que se acomodó lo pedido.

Abrazo

**Comment by LeandroBraier** [comment]
Perfecto Braulio. Gracias!

Mañana manden los demás avances apenas los tengan.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
http://benteveo.tv/_danica-beta/danica/recetario.html
http://benteveo.tv/_danica-beta/danica/cocina-con-los-chicos-1.html

Fijate ahi lea.
Falta lo del home que en breve lo subimos.

**Comment by LeandroBraier** [comment]
Buenísimo Fede! Gracias! Quedó lindo.

Va feedback:

1) Recién cuando se suba a producción esto se van a poder ver las distintas
recetas? No hay forma de mostrarla antes, aunque sea Fake, con distintas
fotos y nombres de recetas?

2) Respecto del Header con la madera en ese color me parece que no pega
para nada con el nuevo KeyVisual. Tendrías que cambiar el color del header
a la estética del KeyVisual actual.

3) Más allá de este detalle de todos los headers del sitio salvo la home,
en el header de Comunidad sigue el errorcito de imagen que te pasé ayer.

4) En el Header de la home:

a. Todavía no subiste imágenes para la adaptación mobile, no? Por favor
suban distintas capturas del video del header que te pasé ayer. Con eso
vamos a estar bien.

b. Como dijo Eze, hay que cambiar la proporción del video. Decime a qué
proporción hay que adaptarlo para que en todas las resoluciones se vea por
lo menos el comienzo de las tres ventanas de abajo. Con ese dato te pido la
adaptación del video y te lo mando de nuevo.

5) A nivel general me parece que todavía falta que lo mires un poco
estéticamente y le des homegeneidad. Lo que veo es que van haciendo los
cambios que les pedimos en la web pero no se preocupan de que lo nuevo y lo
viejo combinen bien, simplemente lo cambian y listo. Necesito que le pongas
un poco de cabeza a eso y que se vea que hay una concepción estética
homogénea. Yo después te pido correcciones frente a eso, pero me refiero a
que noto como que directamente esa variable no la estuvieran contemplando.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
1- No hay drama
2- ¿Cual madera?
3-  Ok, no recuerdo haberlo leido, pero me fijo.
4A- Ok, tampoco recuerdo un mail con las img. Lo chequeo.
4B- Entiendo lo que dicen, pero lo que cada uno ve es relativo a su monitor. Yo lo veo, pero si tenes resoluciones menores, capas que no. Si hacemos que se vea en resoluciones menores, entonces personas como yo vamos a ver el video con el alto cortado, porque yo tengo más ancho de monitor. Más allá de esta problematica, el video no hay que adaptarlo.
5- Oka. vemos de meter más colores de los nuevos.

**Comment by LeandroBraier** [comment]
1- Genial.
2- La madera color cian que está entre los dos tolditos.
3- Te pasé la captura y me dijiste que era la única de las 3 capturas en la
cual entendías cual era el error.
4- a. No te mandé las imágenes, te mandé el video.
4.b. Genial, adaptemos entonces la proporción nomás y cortemos el alto de
una forma en que no quede mal y listo. Creo que hay espacio arriba y abajo
que se puede cortar.
5. Genial!

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-05-29 13:10 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Lea fijate en el home que ya estan puestos los productos. Braulio tuvo un imprevisto y tuvo que salir, faltaría estilizarlo un poco más lo del home.

Lo puntos anteriores no llegué a laburarlos, pero fijate si te gusta el nuevo header, al cual aun le falta cambiar la madera cian y ponerlo mejor, pero ahi va: http://benteveo.tv/_danica-beta/danica/recetario.html

**Comment by FAAREIA** [comment]
Por otra parte, creo que la semana que viene vamos a tener que meter horas extras para llegar bien. Avisale a Eze a ver que dice.

**Comment by LeandroBraier** [comment]
Ok. Mejora un poco la tipografía nueva, pero me parece que se angostó
demasiado ahora el header. Es demasiado finito, me parece que se fueron al
otro extremo. Antes me ocupaba el 80% de la ventana y ahora el 15%. Vayamos
a un punto medio.

Las horas extras laburenlas y después las hablan con Eze para cobrar, no
hay problema. De última se balancean como hacemos siempre para recuperar.
Más allá de eso hoy no vi mucho avance. Metanle pata porque con el tema
restyling de Dánica hoy no avanzamos casi nada (al menos que yo vea) y me
va a costar pedirle a Ezequiel horas extras. Mejor metanle a full y tengan
la versión mostrable completa el lunes temprano. Ahí si, cuando le paso a
Eze le aviso que estuvieron trabajando de más y que después lo arreglan con
él.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Entiendo lo que decis Lea, pero hay cosas que llevan tiempo y el resultado visual no parece mucho. Con respecto a la fuente del header, es la más similar que encontré a la usada en la campaña, creo que no había otra similar. Lo del encabezado fijate en realidad ocupa 30px 35px menos que el anterior. Lo que si le hice fue "achicarlo" un poco ya que todo era muy grande (los iconos) y eso hace que el contenido tome algo más de protagnismo. Miratelo otra vez y si te sigue pareciendo diminuto, lo agrandamos otra vez. ^^

**Comment by LeandroBraier** [comment]
Entiendo, Fede. De todas formas si yo no lo veo no lo puedo justificar. Hagamos así: pasame todos los viernes o lunes un registro de las horas utilizadas por vos y Braulio para cada cosa la semana anterior. Con eso yo lo puedo manejar tranqui con Eze.

Respecto de la tipografía la veo OK. En cuanto al header dejemoslo así por ahora y cuando te paso el video final que va hacemos los ajustes finales. Sería hoy a última hora eso.

abrazo

**Comment by FAAREIA** [comment]
Hola Lea, te paso lo último:

http://benteveo.tv/_danica-beta/danica/home.html
http://benteveo.tv/_danica-beta/danica/comunidad.html
http://benteveo.tv/_danica-beta/danica/recetario.html
http://benteveo.tv/_danica-beta/danica/beneficios.html

Las cucharas se pueden ver aca, pero creo estamos buscando de hacer algo mejor. Es bastante complicado igual. Tiene la versión vieja del encabezado, footer e intro.
http://benteveo.tv/_danica-beta/danica/cocina-con-los-chicos-1.html

**Comment by FAAREIA** [comment]
Dale F5

**Comment by LeandroBraier** [comment]
Fede, me cagaste. Me mandaste todo sin terminar y te fuiste. La entrega era EL JUEVES PASADO. La estiramos hasta hoy a las 18 hs y me das algo sin terminar que no puedo mostrar. Esto no puede volver a pasar. Te llamo por teléfono y no me contestás. Urgente llamame por favor.

Veo mejoras estéticas pero hay mucho que te dije y que falta corregir. Te paso feedback:

HOME: 

1) No cambiaste el spot de la intro como te pedí. Te pasé el link de youtube y todo. Estoy hablando del pop up del principio. Buscalo y reemplazalo por favor. Tampoco lo reemplazaste en el header. Te pedí usar ese mismo spot en el header Eso te lo pedí hoy.

2) No cambiaste la estética de los recuadros de Recetas, Beneficios y Comunidad. Se ven como cosas totalmente diferentes sin relación con la estética de la página. Modificalo, que quede bien.

3) El embed de Facebook no funciona.

RECETARIO

4) Mostrame las 5 recetas saladas y 5 dulces que te pasé en el recetario y con fotos diferentes. Si es más dificil hacerlo fake que hacerlo ya en el servidor de Dánica hacelo en el servidor de Dánica, así el buscador funciona bien también.

COMUNIDAD

5) Los bloques de redes quedan desordenados, no queda un cuadrado o rectángulo completo. Te había pedido esto. Además MK estuvo trabajando el fin de semana para que esto funcione de verdad, no con Loren Impsum. Hacelo funcionar.

TODOS

6) En todos los headers veo una línea como esta:

![captura de pantalla 2015-06-01 a la s 19 27 57](https://cloud.githubusercontent.com/assets/6719872/7924653/7fe59302-0893-11e5-853b-9513e727d94a.png)

No lo puedo entregar así. Corregilo por favor. 

7) Que los links funcionen.

**Comment by mkreyness** [comment]
Ojo Lean lo mio no esta terminado, yo entendi que tenia que estar para 
ESTE jueves 4.
Acordate que me falta data para levantar los feeds de pinterest, lo de 
facebook y twitter tambien esta puesto a manopla.

**Comment by LeandroBraier** [comment]
Ok. Igual no está presentable estéticamente. Se tiene que ver como un
rectángulo sólido, como el de la página de Benteveo. Ya se lo había pedido
a Fede.

Respecto de lo funcional no lo pensemos para el jueves 4, pensemoslo para
el miércoles 3, porque lo tenemos que ver y testear con Eze antes de
entregarlo.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-01 19:36 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
si mi intencion es liquidarlo cuanto antes.

**Comment by LeandroBraier** [comment]
Gracias a los dos! Cierro este ticket.
