### ISSUE TITLE
OpenGraph Facebook en el sitio

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/DanicaWeb#5]
Esto no es prioritario, pero para dentro de dos semanas estaría bueno tenerlo: integrar open graph con Facebook, para que la gente se logee con facebook en el sitio y sus likes aparezcan en la página, además de otras integraciones que permite.

Porfa investigalo y decime si es posible.

Referencia: https://www.facebook.com/help/190339107762990/

**Comment by FAAREIA** [comment]
No hay login en el sitio y como se verían diferentes sus likes? Qué tipo de integración buscan?

**Comment by LeandroBraier** [comment]
Más que nada generar login con redes sociales. Te lo dejo para que lo investigues. Lo vemos en un par de semanas, no ahora. Si ves que necesita algo de programación me avisas y lo vemos con MK, pero por lo que vi es todo HTML, son scripts. abrazo

**Comment by LeandroBraier** [comment]
Esto lo cierro y lo sumo para una versión 2.0 con login

abrazo
