### ISSUE TITLE
Feedback Final Restyling Danica

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/DanicaWeb#51]
Fede, te paso un ppt en Google Drive con todos los detalles del feedback brindado por el cliente. Lo ideal es que esté para hoy pero, como te decía, lo de recetas puede quedar para mañana.

https://docs.google.com/presentation/d/1Nre1BBeV5S4f6gQZvT-uQ84L8gnSa2dVg5tIWAcg_ZY/edit?usp=sharing

Consultame cualquier cosa estoy acá o hacemos un skype si necesitás.

abrazo

**Comment by LeandroBraier** [comment]
Actualizo la URL del video del pop up del spot de Danica.

https://www.youtube.com/watch?v=l2Y82e3lWzI

Cambialo junto con el resto de los cambios del ppt, no hay problema.

abrazo

**Comment by FAAREIA** [comment]
Hola Lea, ahi van los avances hasta la fecha: http://danica.com.ar/cgi-bin/homebasenew.pl
Solo falta reemplazar la imagen del pote, hacer el slideshow de los productos y hacer beneficios.
Una vez aprobado habría que hacer lo responsivo que falte, como por ejemplo el carrusel y el slideshow.

**Comment by FAAREIA** [comment]
Ah y necesito que me consigas las manos de comunidad, no las tengo en vector y transparentar eso no va a quedar 100% bien y va a ser un laburaso. Si las tenes por ahi buenisimo.

**Comment by LeandroBraier** [comment]
Genial, Fede. La imagen del pote, el slideshow de productos y beneficios va
a estar mañana entonces?

Ahora te busco y paso las manitos de comunidad.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-15 12:57 GMT-03:00 Federico Arena notifications@github.com:

**Comment by LeandroBraier** [comment]
Te subí el PSD de las manitos tomado de tu PSD original para la Home de
Danica del año pasado. Está en

BENTEVEO MAQUETADOR/DANICA

Lo busqué en deposit pero evidentemente no lo tomaron de ahí. Eso me lo
habías pasado vos. Fijate si el PSD te sirve.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-15 13:02 GMT-03:00 Leandro Braier leandrobraier@gmail.com:

**Comment by LeandroBraier** [comment]
Respecto de los cambios los veo muy bien. Solo te pido estos detalles:

1) Mirá este corte acá:

![captura de pantalla 2015-06-15 a la s 13 23 18](https://cloud.githubusercontent.com/assets/6719872/8164600/6c92c716-1360-11e5-9ce1-fe61f727ac1d.png)

2) FOOTER: Estirá el pastito un poco más para que quede de fondo en todo el logo de BRF.

![captura de pantalla 2015-06-15 a la s 13 24 53](https://cloud.githubusercontent.com/assets/6719872/8164620/8b8d8ed0-1360-11e5-87ad-80816b1508c0.png)

3) Comunidad: http://danica.com.ar/danica/comunidadnew.html

Da un error raro.

"responseText: Err: error"

4) Beneficios:

Lo que te pasé no era la imagen definitiva de la pizarra. Falta un marco mejor para la pizarra, no queda bien el recorte simple de la foto. Fijate que en deposit hay otras variantes.

abrazo

**Comment by FAAREIA** [comment]
Hola Lea, si mañana lo terminaríamos. Lo de las manos me fijo, creo que las había hecho el ilustrador en su momento.

**Comment by FAAREIA** [comment]
http://www.danica.com.ar/cgi-bin/homebasenew.pl
Ahi esta todo Lea.

Abrazo!

**Comment by LeandroBraier** [comment]
Fede, qué pasó acá? Las manos de todos los negros caídas!

![captura de pantalla 2015-06-16 a la s 14 32 23](https://cloud.githubusercontent.com/assets/6719872/8189505/1c73dd14-1433-11e5-94b7-4fa84980263c.png)

Lo demás en general lo veo bien. La página de Beneficios la vamos a terminar cuando tengamos los textos finales pero fijate si encontrás algún ícono o símbolo para poner en el header.

abrazo

**Comment by LeandroBraier** [comment]
Un temita nomás:

En Recetas poné las cucharas más grandes, no se ven la verdad.

**Comment by FAAREIA** [comment]
Ahi esta corregido el bug Lea. Lo de las cucharas recien podría hacerlo dentro de 3 o 4hs, lo de beneficios lo mismo. De hecho si ya tienen definido que agregarle mejor asi no invierto tiempo probando en algo que después capas que no.

**Comment by LeandroBraier** [comment]
Dale, no hay problema.

Para la noche están bien esos cambios.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-16 15:05 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Ya estan aplicados Lea. F5.

**Comment by LeandroBraier** [comment]
Gracias Fede. Te paso cosas que aparecieron ahora:

1) El tilde del recetas más visitadas en la página de categorías de recetas:

![captura de pantalla 2015-06-17 a la s 09 15 00](https://cloud.githubusercontent.com/assets/6719872/8206453/efeab946-14cf-11e5-9b63-db4288118ee8.png)

2) En el slideshow de productos en la home no aparecen el resto de los productos aún. Aparece solo repetida la Dánica Dorada:

![captura de pantalla 2015-06-17 a la s 09 15 52](https://cloud.githubusercontent.com/assets/6719872/8206464/11ce46cc-14d0-11e5-9281-edcc45acb66e.png)

3) El slideshow de recetas en la home está bien pero el pedido era que rotaran automáticamente esas. 

Si esto tenés para mañana está bien, porque está muy presentable la página, muy bien.

4) Sumar filtro por dificultad al lado de cada categoría.

5) Asistente: El título pasar a minúscula como el resto. El fondo también cambiar al color del restyling.
Además el nombre de la página tiene una letra de más.

![captura de pantalla 2015-06-17 a la s 11 48 48](https://cloud.githubusercontent.com/assets/6719872/8209842/955a7afa-14e5-11e5-8172-2beecccf4bcc.png)

abrazo

**Comment by braulio-evangelisti** [comment]
Lea tenes las imagenes finales de margarinas para el slide de productos?

**Comment by LeandroBraier** [comment]
Si, ya te las paso por WeTransfer en 15.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Ahi fueron!

Confirmame cuando esté subido porfa.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-18 8:54 GMT-03:00 Leandro Braier leandrobraier@gmail.com:

> Si, ya te las paso por WeTransfer en 15.
> 
> Leandro Braier
> Producción Audiovisual & Social Media
> Benteveo Producciones http://benteveo.tv
> Móvil 1158717399
> 
> On Thu, Jun 18, 2015 at 8:44 AM, Braulio Evangelisti <

**Comment by braulio-evangelisti** [comment]
Lo estoy por subir, algun orden especifico?

**Comment by LeandroBraier** [comment]
Si, las 3 primeras que tienen que aparecer son las 3 que están ahora.
Después vienen Fitacol, Dorada Pote, Vegetalina y Manterina. En ese orden.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by braulio-evangelisti** [comment]
Listo Lea ahi esta todo subido.

Abrazo

**Comment by LeandroBraier** [comment]
Braulio, fijate que los potes de Dorada y Fitacol quedaron más chicos que
el de SoftLight celestito. Tienen que quedar los 3 iguales. Y si podés
achicá un poco la Vegetalina que quede más pareja con el resto.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-18 11:36 GMT-03:00 Braulio Evangelisti notifications@github.com:

**Comment by LeandroBraier** [comment]
Fijate que pasé otras correcciones a parte de estas más arriba en el
ticket. Si podés corregir eso también porfa. Son detalles.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-18 11:43 GMT-03:00 Leandro Braier leandrobraier@gmail.com:

**Comment by braulio-evangelisti** [comment]
Ah ok, tipo 12 habia subido lo de las imagenes, mañana me fijo lo demas.

Abrazo

**Comment by LeandroBraier** [comment]
Ok, si corregiste los productos está bien.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by braulio-evangelisti** [comment]
Lea ya estaria casi todo, faltaria, si tienen los originales de estas dos imagenes .ai o .psd del asistente

http://www.danica.com.ar/danica/template/img/asistencia-inicio.png
http://www.danica.com.ar/danica/template/img/asistencia-cierre.png

que suban directamente los png con el color nuevo reemplazando las que estan y listo. 
Fede no los tiene.

Abrazo

**Comment by LeandroBraier** [comment]
No entiendo para qué lo necesitás. No fue reemplazado por otro toldito?

Esto no lo corrigieron todavía:

![captura de pantalla 2015-06-19 a la s 14 59 54](https://cloud.githubusercontent.com/assets/6719872/8259420/b999881c-1692-11e5-8f19-cd3be8481b73.png)

Se corta la parte de arriba de las letras.

**Comment by braulio-evangelisti** [comment]
Ah estaba mas arriba ese cambio no lo vi, ahora lo acomodo.

No es el toldo del menu ni el del contenido de la pagina. El diseño del asistente esta como incrustado sobre el fondo mediante dos cortes con ese efecto, como pase el fondo al color nuevo, quedaron esos bordes con el color viejo mas obscuro, fijate aca:

http://www.danica.com.ar/cgi-bin/formasistentenew.pl

No hace falta que me manden nada, con cambiarle el color y resubirlo reemplazando los que estan andaria bien.

**Comment by braulio-evangelisti** [comment]
Listo el cambio de las palabras cortadas en la home.

**Comment by LeandroBraier** [comment]
Genial. Los tolditos los estoy buscando pero no los tengo. Igual me parece
que quedarían mejor reemplazados por la nueva estética. Ponele el toldito
nuevo mejor.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-19 15:23 GMT-03:00 Braulio Evangelisti notifications@github.com:

**Comment by braulio-evangelisti** [comment]
Lea fijate el asistente ahi cambie lo que pusiste mas arriba.

Abrazo

**Comment by LeandroBraier** [comment]
Quedó muy bien Braulio!

Lo único borrale la linea blanca que queda arriba y ya estamos. Gracias!

![captura de pantalla 2015-06-22 a la s 12 04 39](https://cloud.githubusercontent.com/assets/6719872/8284811/7bd0b51a-18d5-11e5-9c52-f683d2c38b99.png)

**Comment by braulio-evangelisti** [comment]
Fijate ahora si se ve la linea

Abrazo

**Comment by LeandroBraier** [comment]
En el de arriba ya no se nota, pero en el toldito de abajo sigue el
problema.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by braulio-evangelisti** [comment]
Fijate ahora, con el brillo que tengo seteado en mi monitor no lo notaba.

**Comment by LeandroBraier** [comment]
Perfecto, ahora si.

Gracias!

Les aviso si el cliente pide más cambios y cuando hay que subirlo a producción.

abrazo
