### ISSUE TITLE
Restyling DanicaWeb- Responsive

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/DanicaWeb#52]
Fede, en Safari mirá como se ve:

![safari_mac](https://cloud.githubusercontent.com/assets/6719872/8339994/edf9d2da-1a91-11e5-8e72-4a17894799c0.png)

No es urgente, pero te voy avisando por si sabés qué puede estar pasando.

**Comment by FAAREIA** [comment]
Ok, me fijo. Igual dale F5 por las dudas, me parece raro que se te vea asi.

**Comment by LeandroBraier** [comment]
Ya lo vimos Eze y yo. Probalo vos en browserstack vas a ver.

**Comment by FAAREIA** [comment]
Luego lo pruebo en una mac virtual. No confió en browsertack.
Para cuando tendría que estar resuelto?

**Comment by LeandroBraier** [comment]
Para mañana a la tarde está bien. Tan complejo es? Me suena a que es algo
de código. Pareciera que el video del slideshow tiene un tamaño distinto y
está empujando todo.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-25 9:44 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Puede resolverse en 5m como en 4hs, asi son los bugs webs ^^
El video no creo que sea, ahi hay texto y botones superpuestos. Medio raro.
Me fijo y te aviso

**Comment by LeandroBraier** [comment]
Dale, gracias. Igual como te decía. Puede ser para mañana a la tarde todo
bien. Tenemos otras prioridades. Decime cuando te puedo llamar por skype y
repasamos todo por las dudas.

Ayer lo hice con Marce.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-25 9:52 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Lea, ahi estuvimos probando con Braulio y no le encontramos la vuelta por ahora. Es posible que no sea solucionable o capas que luego de horas se soluciona. Es imprevisible.
La solución rápida sería meter otro plugin y rehacer el carusel. ¿Queres que lo tratemos de hacer hoy igual?

**Comment by LeandroBraier** [comment]
No, no le demos prioridad por ahora.

Pero para el lunes a la tarde deberíamos tener por lo menos una idea de
cómo solucionarlo, no?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-26 10:12 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Dale, el lúnes lo cambiamos y listo

**Comment by LeandroBraier** [comment]
Excelente Fede. Gracias!

Avancemos a full con Torneo entonces.

Yo ahora te paso mis pendientes. Decime si te puedo ayudar en algo más con
eso.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-26 10:45 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Esta corregido Lea.

Abrazo

**Comment by LeandroBraier** [comment]
Perfecto Fede!

El feed de Facebook se va a ver cuando quedé en producción el sitio no?

abrazo

**Comment by FAAREIA** [comment]
Seguramente, sino lo vemos con marce en el momento
