### ISSUE TITLE
Mailings

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/DanicaWeb#6]
Fede, necesito saber si maquetás mailings. Necesitamos uno para reenviar automáticamente a todos los que llenan el formulario de la aplicación y otra para los que llenan el del asistente. SI maquetás esto después te pidos los que correspondería al Asistente Dánica en sí, que son más complejos, porque necesitamos 1 de bienvenida y 1 template que serían distinto según las recetas del día.

Porfa confirmame cuanto antes si hacés esto. Las imágenes para los mailings de Asistente y Aplicación los subí a tu dropbox. El link de derivación es la página de Facebook de Dánica Argentina.

**Comment by LeandroBraier** [comment]
De esto necesito saber por ahora si hacés este maquetado nomás. A las imagenes que te subí al dropbox no les des bola por ahora.

**Comment by FAAREIA** [comment]
Si maqueto. Es lo mismo que la maquetación común, pero más conservadora y con los estilos inline.
Ok a tu segundo comentario

**Comment by LeandroBraier** [comment]
Excelente, cuando tengo los diseños susodichos te aviso. abrazo

**Comment by LeandroBraier** [comment]
Va el cambio de texto del newsletter, Fede.

"Estás recibiendo este correo electrónico porque activaste el Asistente Dánica.

¿Tenés problemas para visualizar este email? Miralo en tu navegador.

Para desactivar el Asistente Dánica, hacé clic aquí."

**Comment by LeandroBraier** [comment]
Y aca donde dice
"Ya tenemos toda la información necesaria para sugerirte tu menú favorito cuando más los necesitás."

deberia ser

"Ya tenemos toda la información necesaria para sugerirte tu menú favorito cuando más lo necesitás."

ya que estan hablando de "TU" menu, no "TUS" menús.
