### ISSUE TITLE
Subir JPG a URL invisibles en la web de Danica

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/DanicaWeb#7]
Lo necesito para programar unas respuestas de mail automáticas. Me las subirías porfa?

abrazo
![mailing_aplicacion](https://f.cloud.github.com/assets/6719872/2236421/f3208a60-9b5d-11e3-8bbd-82c4f98068ae.jpg)
![mailing_asistente](https://f.cloud.github.com/assets/6719872/2236422/f7083b5a-9b5d-11e3-8260-19df9fcd917e.jpg)

**Comment by FAAREIA** [comment]
Ok, lo voy a tener que maquetar, tiene bastantes links. Esta el PSD?

**Comment by LeandroBraier** [comment]
Este no hace falta maquetarlo, es un JPG con un solo link, no hay problema. Solo necesito tener la imagen accesible en una URL por ahora.

**Comment by FAAREIA** [comment]
Ok, lo hago asi, peeeeeeeeeeeeeero mira que hay varios links.
- Todos lo de la comunidad
- El logo de dánica
- Y el link de abajo de todo que dice "click....aca!"

**Comment by FAAREIA** [comment]
danica.com.ar/danica/template/img/danica-1.jpg
danica.com.ar/danica/template/img/danica-2.jpg

**Comment by LeandroBraier** [comment]
Gracias Fede!
