### ISSUE TITLE
"Pasta a las hierbas" pierde el estilo

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/DanicaWeb#8]
Fede, cuando puedan fijense esta receta que subí nueva.

http://www.danica.com.ar/danica/pasta-a-las-hierbas.html

Pierde el estilo, mientras que otra que subí nueva queda igual. 

http://www.danica.com.ar/danica/discos-nutritivos.html

Revisé el código XML pero está OK.

abrazo

**Comment by mkreyness** [comment]
Te faltaba cerrar una comilla en uno de los primeros renglones del XML 
(decia <parte titulo="Pasta a las hierbas paso a paso>)
Ya lo arregle y anda bien.

**Comment by FAAREIA** [comment]
Joya Marce, acordate Lea que esto es un template, si anda bien con uno, anda bien con todos excepto que suceda lo que marce corrigió.

**Comment by LeandroBraier** [comment]
Exacto, por eso preguntaba. Gracias a los dos!
